
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

interface AccessibilityContextType {
  fontSize: string;
  highContrast: boolean;
  screenReaderMode: boolean;
  language: string;
  simpleMode: boolean;
  setFontSize: (size: string) => void;
  setHighContrast: (enabled: boolean) => void;
  setScreenReaderMode: (enabled: boolean) => void;
  setLanguage: (lang: string) => void;
  setSimpleMode: (simple: boolean) => void;
  announceToScreenReader: (message: string) => void;
  t: (key: string) => string;
}

// Comprehensive translation dictionary for all 12 languages
const translations = {
  en: {
    appTitle: "The Correct Spender",
    appSubtitle: "Your accessible financial wellness companion",
    welcomeTitle: "Take Control of Your Financial Future",
    welcomeDescription: "Whether you're new to managing money or looking to improve your financial health, we're here to help you make informed decisions without the need for expensive advisors.",
    selectLanguage: "Select Language",
    languageDescription: "Choose your preferred language to continue",
    continue: "Continue",
    accessibilitySettings: "Accessibility Settings",
    textSize: "Text Size",
    visualAccessibility: "Visual Accessibility",
    screenReaderSupport: "Screen Reader Support",
    language: "Language",
    interfaceMode: "Interface Mode",
    simple: "Simple",
    detailed: "Detailed",
    small: "Small",
    medium: "Medium",
    large: "Large",
    extraLarge: "Extra Large",
    highContrastMode: "High Contrast Mode",
    enhancedScreenReaderMode: "Enhanced Screen Reader Mode",
    simpleMode: "Simple Mode",
    simpleModeDescription: "Use basic language and simplified interface",
    detailedMode: "Detailed Mode",
    detailedModeDescription: "Show advanced options and technical terms",
    makeColorsStronger: "Make colors stronger",
    colorsAdjusted: "Colors have been adjusted",
    makeTextEasierToSee: "Makes text easier to see with stronger colors",
    increaseContrastDesc: "Increases contrast between text and background for better visibility",
    helpForScreenReaders: "Help for screen readers",
    interfaceAdjustedForScreenReaders: "Interface adjusted for screen readers",
    worksWithScreenReaderSoftware: "Makes the app work better with screen reading software",
    optimizesInterfaceElements: "Optimizes interface elements and adds extra context for screen readers",
    makeAppEasierToUse: "Make the app easier to use for you",
    customizeAccessibilityNeeds: "Customize the app to meet your accessibility needs",
    easyWordsBasicOptions: "Easy words and basic options",
    moreOptionsTechnicalWords: "More options and technical words",
    textSizeOptions: "Text size options",
    fontSizeOptions: "Font size options",
    makeText: "Make text",
    setFontSizeTo: "Set font size to",
    languageOptions: "Language options",
    languageSelection: "Language selection",
    changeLanguageTo: "Change language to",
    setLanguageTo: "Set language to",
    goTo: "Go to",
    quickAccessTips: "Quick Access Tips",
    navigateBetweenElements: "Navigate between elements",
    activateButtons: "Activate buttons",
    closeDialogsReturn: "Close dialogs or return to previous section",
    increaseBrowserZoom: "Increase browser zoom",
    textSizeChanged: "Text size changed",
    textIsNow: "Text is now",
    fontSizeUpdated: "Font Size Updated",
    fontSizeChangedTo: "Font size changed to",
    colorsBackToNormal: "Colors back to normal",
    highContrastOn: "High contrast on",
    highContrastDisabled: "High Contrast Disabled",
    highContrastEnabled: "High Contrast Enabled",
    visualContrastAdjusted: "Visual contrast has been adjusted",
    screenReaderHelpOff: "Screen reader help off",
    screenReaderHelpOn: "Screen reader help on",
    screenReaderModeDisabled: "Screen Reader Mode Disabled",
    screenReaderModeEnabled: "Screen Reader Mode Enabled",
    interfaceOptimizedForScreenReaders: "Interface optimized for screen readers",
    simpleModeOn: "Simple mode on",
    detailedModeOn: "Detailed mode on",
    usingSimpleLanguage: "Using simple language and basic options",
    showingAdvancedOptions: "Showing advanced options and technical terms",
    // Financial Health Assessment
    financialHealthAssessment: "Financial Health Assessment",
    financialHealthDescription: "Enter your financial information to get a personalized health score and recommendations",
    monthlyIncome: "Monthly Income ($)",
    monthlyExpenses: "Monthly Expenses ($)",
    totalSavings: "Total Savings ($)",
    totalDebt: "Total Debt ($)",
    emergencyFund: "Emergency Fund ($)",
    calculateScore: "Calculate My Financial Health Score",
    yourScore: "Your Financial Health Score",
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    needsImprovement: "Needs Improvement",
    savingsRate: "Savings Rate",
    emergencyMonths: "Emergency Months",
    debtToIncome: "Debt to Income",
    recommendations: "Personalized Recommendations:",
    additionalTips: "Additional Tips:",
    wasHelpful: "Was this advice helpful?",
    helpful: "Helpful",
    notHelpful: "Not Helpful",
    getAIHelp: "Get AI Help",
    // Tutorial
    tutorialWelcome: "Welcome to The Correct Spender!",
    tutorialWelcomeDesc: "This app helps you manage your money better. Let's take a quick tour to show you how everything works.",
    tutorialAssessment: "Financial Health Assessment",
    tutorialAssessmentDesc: "Start here to check how you're doing with money. You'll get a score and personalized advice to improve your finances.",
    tutorialBudget: "Budget Helper",
    tutorialBudgetDesc: "Create a budget plan that works for your income. The app will suggest the best budget rule for your situation.",
    tutorialAI: "AI Money Helper",
    tutorialAIDesc: "Ask questions and get instant help with money decisions. It's like having a financial advisor available 24/7.",
    tutorialAccessibility: "Accessibility Settings",
    tutorialAccessibilityDesc: "Make the app work better for you. Change text size, colors, language, and more to fit your needs.",
    tutorialReady: "Ready to Start!",
    tutorialReadyDesc: "We recommend starting with the Financial Health Assessment to understand your current situation and get personalized advice.",
    appTutorial: "App Tutorial",
    skipTutorial: "Skip Tutorial",
    previous: "Previous",
    next: "Next",
    startAssessment: "Start Assessment",
    exploreMyOwn: "Explore on My Own",
    // Navigation and Common
    back: "Back",
    backToOverview: "Back to Overview",
    start: "Start",
    getStarted: "Get Started",
    didYouKnow: "Did You Know?",
    showAnotherFact: "Show Another Fact",
    skipToMain: "Skip to main content",
    // Features
    checkMoneyHealth: "Check Your Money Health",
    checkMoneyHealthDesc: "See how you're doing with money and get help",
    budgetHelper: "Budget Helper",
    budgetHelperDesc: "Make a plan for your money that works for you",
    moneyHelperChat: "Money Helper Chat",
    moneyHelperChatDesc: "Ask questions and get help with money decisions",
    makeAppEasier: "Make App Easier to Use",
    makeAppEasierDesc: "Change how the app looks and works for you",
    // Error messages
    invalidInput: "Invalid Input",
    enterValidIncome: "Please enter a valid monthly income",
    assessmentComplete: "Assessment Complete!",
    scoreMessage: "Your financial health score is",
    thankYou: "Thank you!",
    adviceHelpful: "We're glad the advice was helpful",
    moreAdvice: "More advice coming up!",
    additionalTipsDesc: "Here are additional tips that might help",
    aiHelper: "AI Helper",
    navigateToAI: "Navigate to the AI Chat section for personalized assistance"
  },
  es: {
    appTitle: "El Gastador Correcto",
    appSubtitle: "Tu compañero accesible de bienestar financiero",
    welcomeTitle: "Toma Control de Tu Futuro Financiero",
    welcomeDescription: "Ya sea que seas nuevo manejando dinero o busques mejorar tu salud financiera, estamos aquí para ayudarte a tomar decisiones informadas sin necesidad de asesores costosos.",
    selectLanguage: "Seleccionar Idioma",
    languageDescription: "Elige tu idioma preferido para continuar",
    continue: "Continuar",
    accessibilitySettings: "Configuración de Accesibilidad",
    textSize: "Tamaño de Texto",
    visualAccessibility: "Accesibilidad Visual",
    screenReaderSupport: "Soporte para Lector de Pantalla",
    language: "Idioma",
    interfaceMode: "Modo de Interfaz",
    simple: "Simple",
    detailed: "Detallado",
    small: "Pequeño",
    medium: "Mediano",
    large: "Grande",
    extraLarge: "Extra Grande",
    highContrastMode: "Modo de Alto Contraste",
    enhancedScreenReaderMode: "Modo Mejorado de Lector de Pantalla",
    simpleMode: "Modo Simple",
    simpleModeDescription: "Usar lenguaje básico e interfaz simplificada",
    detailedMode: "Modo Detallado",
    detailedModeDescription: "Mostrar opciones avanzadas y términos técnicos",
    makeColorsStronger: "Hacer los colores más fuertes",
    colorsAdjusted: "Los colores han sido ajustados",
    makeTextEasierToSee: "Hace que el texto sea más fácil de ver con colores más fuertes",
    increaseContrastDesc: "Aumenta el contraste entre texto y fondo para mejor visibilidad",
    helpForScreenReaders: "Ayuda para lectores de pantalla",
    interfaceAdjustedForScreenReaders: "Interfaz ajustada para lectores de pantalla",
    worksWithScreenReaderSoftware: "Hace que la aplicación funcione mejor con software de lectura de pantalla",
    optimizesInterfaceElements: "Optimiza elementos de interfaz y agrega contexto extra para lectores de pantalla",
    makeAppEasierToUse: "Hacer la aplicación más fácil de usar para ti",
    customizeAccessibilityNeeds: "Personaliza la aplicación para satisfacer tus necesidades de accesibilidad",
    easyWordsBasicOptions: "Palabras fáciles y opciones básicas",
    moreOptionsTechnicalWords: "Más opciones y palabras técnicas",
    textSizeOptions: "Opciones de tamaño de texto",
    fontSizeOptions: "Opciones de tamaño de fuente",
    makeText: "Hacer texto",
    setFontSizeTo: "Establecer tamaño de fuente a",
    languageOptions: "Opciones de idioma",
    languageSelection: "Selección de idioma",
    changeLanguageTo: "Cambiar idioma a",
    setLanguageTo: "Establecer idioma a",
    goTo: "Ir a",
    quickAccessTips: "Consejos de Acceso Rápido",
    navigateBetweenElements: "Navegar entre elementos",
    activateButtons: "Activar botones",
    closeDialogsReturn: "Cerrar diálogos o volver a la sección anterior",
    increaseBrowserZoom: "Aumentar zoom del navegador",
    textSizeChanged: "Tamaño de texto cambiado",
    textIsNow: "El texto ahora es",
    fontSizeUpdated: "Tamaño de Fuente Actualizado",
    fontSizeChangedTo: "Tamaño de fuente cambiado a",
    colorsBackToNormal: "Colores de vuelta a la normalidad",
    highContrastOn: "Alto contraste activado",
    highContrastDisabled: "Alto Contraste Desactivado",
    highContrastEnabled: "Alto Contraste Activado",
    visualContrastAdjusted: "Contraste visual ha sido ajustado",
    screenReaderHelpOff: "Ayuda de lector de pantalla desactivada",
    screenReaderHelpOn: "Ayuda de lector de pantalla activada",
    screenReaderModeDisabled: "Modo Lector de Pantalla Desactivado",
    screenReaderModeEnabled: "Modo Lector de Pantalla Activado",
    interfaceOptimizedForScreenReaders: "Interfaz optimizada para lectores de pantalla",
    simpleModeOn: "Modo simple activado",
    detailedModeOn: "Modo detallado activado",
    usingSimpleLanguage: "Usando lenguaje simple y opciones básicas",
    showingAdvancedOptions: "Mostrando opciones avanzadas y términos técnicos",
    // Financial Health Assessment
    financialHealthAssessment: "Evaluación de Salud Financiera",
    financialHealthDescription: "Ingresa tu información financiera para obtener un puntaje personalizado y recomendaciones",
    monthlyIncome: "Ingresos Mensuales ($)",
    monthlyExpenses: "Gastos Mensuales ($)",
    totalSavings: "Ahorros Totales ($)",
    totalDebt: "Deuda Total ($)",
    emergencyFund: "Fondo de Emergencia ($)",
    calculateScore: "Calcular Mi Puntaje de Salud Financiera",
    yourScore: "Tu Puntaje de Salud Financiera",
    excellent: "Excelente",
    good: "Bueno",
    fair: "Regular",
    needsImprovement: "Necesita Mejora",
    savingsRate: "Tasa de Ahorro",
    emergencyMonths: "Meses de Emergencia",
    debtToIncome: "Deuda a Ingresos",
    recommendations: "Recomendaciones Personalizadas:",
    additionalTips: "Consejos Adicionales:",
    wasHelpful: "¿Fue útil este consejo?",
    helpful: "Útil",
    notHelpful: "No Útil",
    getAIHelp: "Obtener Ayuda de IA",
    // Tutorial
    tutorialWelcome: "¡Bienvenido a El Gastador Correcto!",
    tutorialWelcomeDesc: "Esta aplicación te ayuda a manejar mejor tu dinero. Hagamos un recorrido rápido para mostrarte cómo funciona todo.",
    tutorialAssessment: "Evaluación de Salud Financiera",
    tutorialAssessmentDesc: "Comienza aquí para verificar cómo te va con el dinero. Obtendrás un puntaje y consejos personalizados para mejorar tus finanzas.",
    tutorialBudget: "Ayudante de Presupuesto",
    tutorialBudgetDesc: "Crea un plan de presupuesto que funcione para tus ingresos. La aplicación sugerirá la mejor regla de presupuesto para tu situación.",
    tutorialAI: "Ayudante de Dinero IA",
    tutorialAIDesc: "Haz preguntas y obtén ayuda instantánea con decisiones de dinero. Es como tener un asesor financiero disponible 24/7.",
    tutorialAccessibility: "Configuración de Accesibilidad",
    tutorialAccessibilityDesc: "Haz que la aplicación funcione mejor para ti. Cambia el tamaño del texto, colores, idioma y más para satisfacer tus necesidades.",
    tutorialReady: "¡Listo para Comenzar!",
    tutorialReadyDesc: "Recomendamos comenzar con la Evaluación de Salud Financiera para entender tu situación actual y obtener consejos personalizados.",
    appTutorial: "Tutorial de la Aplicación",
    skipTutorial: "Saltar Tutorial",
    previous: "Anterior",
    next: "Siguiente",
    startAssessment: "Comenzar Evaluación",
    exploreMyOwn: "Explorar por Mi Cuenta",
    // Navigation and Common
    back: "Atrás",
    backToOverview: "Volver al Resumen",
    start: "Comenzar",
    getStarted: "Empezar",
    didYouKnow: "¿Sabías Que?",
    showAnotherFact: "Mostrar Otro Dato",
    skipToMain: "Saltar al contenido principal",
    // Features
    checkMoneyHealth: "Verificar Salud del Dinero",
    checkMoneyHealthDesc: "Ve cómo te va con el dinero y obtén ayuda",
    budgetHelper: "Ayudante de Presupuesto",
    budgetHelperDesc: "Haz un plan para tu dinero que funcione para ti",
    moneyHelperChat: "Chat Ayudante de Dinero",
    moneyHelperChatDesc: "Haz preguntas y obtén ayuda con decisiones de dinero",
    makeAppEasier: "Hacer la App Más Fácil de Usar",
    makeAppEasierDesc: "Cambia cómo se ve y funciona la app para ti",
    // Error messages
    invalidInput: "Entrada Inválida",
    enterValidIncome: "Por favor ingresa un ingreso mensual válido",
    assessmentComplete: "¡Evaluación Completa!",
    scoreMessage: "Tu puntaje de salud financiera es",
    thankYou: "¡Gracias!",
    adviceHelpful: "Nos alegra que el consejo haya sido útil",
    moreAdvice: "¡Más consejos en camino!",
    additionalTipsDesc: "Aquí hay consejos adicionales que podrían ayudar",
    aiHelper: "Ayudante IA",
    navigateToAI: "Navega a la sección de Chat IA para asistencia personalizada"
  },
  fr: {
    appTitle: "Le Dépenseur Correct",
    appSubtitle: "Votre compagnon de bien-être financier accessible",
    welcomeTitle: "Prenez le Contrôle de Votre Avenir Financier",
    welcomeDescription: "Que vous soyez nouveau dans la gestion de l'argent ou que vous cherchiez à améliorer votre santé financière, nous sommes là pour vous aider à prendre des décisions éclairées sans avoir besoin de conseillers coûteux.",
    selectLanguage: "Sélectionner la Langue",
    languageDescription: "Choisissez votre langue préférée pour continuer",
    continue: "Continuer",
    accessibilitySettings: "Paramètres d'Accessibilité",
    textSize: "Taille du Texte",
    visualAccessibility: "Accessibilité Visuelle",
    screenReaderSupport: "Support de Lecteur d'Écran",
    language: "Langue",
    interfaceMode: "Mode d'Interface",
    simple: "Simple",
    detailed: "Détaillé",
    small: "Petit",
    medium: "Moyen",
    large: "Grand",
    extraLarge: "Extra Grand",
    highContrastMode: "Mode Haut Contraste",
    enhancedScreenReaderMode: "Mode Lecteur d'Écran Amélioré",
    simpleMode: "Mode Simple",
    simpleModeDescription: "Utiliser un langage de base et une interface simplifiée",
    detailedMode: "Mode Détaillé",
    detailedModeDescription: "Afficher les options avancées et les termes techniques",
    makeColorsStronger: "Rendre les couleurs plus fortes",
    colorsAdjusted: "Les couleurs ont été ajustées",
    makeTextEasierToSee: "Rend le texte plus facile à voir avec des couleurs plus fortes",
    increaseContrastDesc: "Augmente le contraste entre le texte et l'arrière-plan pour une meilleure visibilité",
    helpForScreenReaders: "Aide pour les lecteurs d'écran",
    interfaceAdjustedForScreenReaders: "Interface ajustée pour les lecteurs d'écran",
    worksWithScreenReaderSoftware: "Fait fonctionner l'application mieux avec les logiciels de lecture d'écran",
    optimizesInterfaceElements: "Optimise les éléments d'interface et ajoute du contexte supplémentaire pour les lecteurs d'écran",
    makeAppEasierToUse: "Rendre l'application plus facile à utiliser pour vous",
    customizeAccessibilityNeeds: "Personnalisez l'application pour répondre à vos besoins d'accessibilité",
    easyWordsBasicOptions: "Mots faciles et options de base",
    moreOptionsTechnicalWords: "Plus d'options et mots techniques",
    textSizeOptions: "Options de taille de texte",
    fontSizeOptions: "Options de taille de police",
    makeText: "Rendre le texte",
    setFontSizeTo: "Définir la taille de police à",
    languageOptions: "Options de langue",
    languageSelection: "Sélection de langue",
    changeLanguageTo: "Changer la langue en",
    setLanguageTo: "Définir la langue à",
    goTo: "Aller à",
    quickAccessTips: "Conseils d'Accès Rapide",
    navigateBetweenElements: "Naviguer entre les éléments",
    activateButtons: "Activer les boutons",
    closeDialogsReturn: "Fermer les dialogues ou retourner à la section précédente",
    increaseBrowserZoom: "Augmenter le zoom du navigateur",
    textSizeChanged: "Taille du texte modifiée",
    textIsNow: "Le texte est maintenant",
    fontSizeUpdated: "Taille de Police Mise à Jour",
    fontSizeChangedTo: "Taille de police changée à",
    colorsBackToNormal: "Couleurs revenues à la normale",
    highContrastOn: "Haut contraste activé",
    highContrastDisabled: "Haut Contraste Désactivé",
    highContrastEnabled: "Haut Contraste Activé",
    visualContrastAdjusted: "Contraste visuel a été ajusté",
    screenReaderHelpOff: "Aide lecteur d'écran désactivée",
    screenReaderHelpOn: "Aide lecteur d'écran activée",
    screenReaderModeDisabled: "Mode Lecteur d'Écran Désactivé",
    screenReaderModeEnabled: "Mode Lecteur d'Écran Activé",
    interfaceOptimizedForScreenReaders: "Interface optimisée pour les lecteurs d'écran",
    simpleModeOn: "Mode simple activé",
    detailedModeOn: "Mode détaillé activé",
    usingSimpleLanguage: "Utilisant un langage simple et des options de base",
    showingAdvancedOptions: "Affichant des options avancées et des termes techniques",
    // Financial Health Assessment
    financialHealthAssessment: "Évaluation de la Santé Financière",
    financialHealthDescription: "Entrez vos informations financières pour obtenir un score personnalisé et des recommandations",
    monthlyIncome: "Revenus Mensuels ($)",
    monthlyExpenses: "Dépenses Mensuelles ($)",
    totalSavings: "Épargne Totale ($)",
    totalDebt: "Dette Totale ($)",
    emergencyFund: "Fonds d'Urgence ($)",
    calculateScore: "Calculer Mon Score de Santé Financière",
    yourScore: "Votre Score de Santé Financière",
    excellent: "Excellent",
    good: "Bon",
    fair: "Passable",
    needsImprovement: "Nécessite une Amélioration",
    savingsRate: "Taux d'Épargne",
    emergencyMonths: "Mois d'Urgence",
    debtToIncome: "Dette sur Revenus",
    recommendations: "Recommandations Personnalisées:",
    additionalTips: "Conseils Supplémentaires:",
    wasHelpful: "Ce conseil était-il utile?",
    helpful: "Utile",
    notHelpful: "Pas Utile",
    getAIHelp: "Obtenir l'Aide de l'IA",
    // Tutorial
    tutorialWelcome: "Bienvenue sur Le Dépenseur Correct!",
    tutorialWelcomeDesc: "Cette application vous aide à mieux gérer votre argent. Faisons un tour rapide pour vous montrer comment tout fonctionne.",
    tutorialAssessment: "Évaluation de la Santé Financière",
    tutorialAssessmentDesc: "Commencez ici pour vérifier comment vous vous en sortez avec l'argent. Vous obtiendrez un score et des conseils personnalisés pour améliorer vos finances.",
    tutorialBudget: "Assistant Budget",
    tutorialBudgetDesc: "Créez un plan budgétaire qui fonctionne pour vos revenus. L'application suggérera la meilleure règle budgétaire pour votre situation.",
    tutorialAI: "Assistant Argent IA",
    tutorialAIDesc: "Posez des questions et obtenez une aide instantanée avec les décisions d'argent. C'est comme avoir un conseiller financier disponible 24h/24 et 7j/7.",
    tutorialAccessibility: "Paramètres d'Accessibilité",
    tutorialAccessibilityDesc: "Faites fonctionner l'application mieux pour vous. Changez la taille du texte, les couleurs, la langue et plus pour répondre à vos besoins.",
    tutorialReady: "Prêt à Commencer!",
    tutorialReadyDesc: "Nous recommandons de commencer par l'Évaluation de la Santé Financière pour comprendre votre situation actuelle et obtenir des conseils personnalisés.",
    appTutorial: "Tutoriel de l'Application",
    skipTutorial: "Ignorer le Tutoriel",
    previous: "Précédent",
    next: "Suivant",
    startAssessment: "Commencer l'Évaluation",
    exploreMyOwn: "Explorer par Moi-même",
    // Navigation and Common
    back: "Retour",
    backToOverview: "Retour à l'Aperçu",
    start: "Commencer",
    getStarted: "Commencer",
    didYouKnow: "Le Saviez-vous?",
    showAnotherFact: "Afficher un Autre Fait",
    skipToMain: "Aller au contenu principal",
    // Features
    checkMoneyHealth: "Vérifier la Santé de l'Argent",
    checkMoneyHealthDesc: "Voyez comment vous vous en sortez avec l'argent et obtenez de l'aide",
    budgetHelper: "Assistant Budget",
    budgetHelperDesc: "Faites un plan pour votre argent qui fonctionne pour vous",
    moneyHelperChat: "Chat Assistant Argent",
    moneyHelperChatDesc: "Posez des questions et obtenez de l'aide avec les décisions d'argent",
    makeAppEasier: "Rendre l'App Plus Facile à Utiliser",
    makeAppEasierDesc: "Changez comment l'app apparaît et fonctionne pour vous",
    // Error messages
    invalidInput: "Entrée Invalide",
    enterValidIncome: "Veuillez entrer un revenu mensuel valide",
    assessmentComplete: "Évaluation Terminée!",
    scoreMessage: "Votre score de santé financière est",
    thankYou: "Merci!",
    adviceHelpful: "Nous sommes heureux que le conseil ait été utile",
    moreAdvice: "Plus de conseils arrivent!",
    additionalTipsDesc: "Voici des conseils supplémentaires qui pourraient aider",
    aiHelper: "Assistant IA",
    navigateToAI: "Naviguez vers la section Chat IA pour une assistance personnalisée"
  },
  de: {
    appTitle: "Der Richtige Spender",
    appSubtitle: "Ihr barrierefreier Begleiter für finanzielles Wohlbefinden",
    welcomeTitle: "Übernehmen Sie die Kontrolle über Ihre finanzielle Zukunft",
    welcomeDescription: "Ob Sie neu im Umgang mit Geld sind oder Ihre finanzielle Gesundheit verbessern möchten, wir sind hier, um Ihnen zu helfen, informierte Entscheidungen zu treffen, ohne teure Berater zu benötigen.",
    selectLanguage: "Sprache Auswählen",
    languageDescription: "Wählen Sie Ihre bevorzugte Sprache, um fortzufahren",
    continue: "Weiter",
    accessibilitySettings: "Barrierefreiheits-Einstellungen",
    textSize: "Textgröße",
    visualAccessibility: "Visuelle Barrierefreiheit",
    screenReaderSupport: "Bildschirmleser-Unterstützung",
    language: "Sprache",
    interfaceMode: "Interface-Modus",
    simple: "Einfach",
    detailed: "Detailliert",
    small: "Klein",
    medium: "Mittel",
    large: "Groß",
    extraLarge: "Extra Groß",
    highContrastMode: "Hoher Kontrast Modus",
    enhancedScreenReaderMode: "Verbesserter Bildschirmleser-Modus",
    simpleMode: "Einfacher Modus",
    simpleModeDescription: "Einfache Sprache und vereinfachte Benutzeroberfläche verwenden",
    detailedMode: "Detaillierter Modus",
    detailedModeDescription: "Erweiterte Optionen und technische Begriffe anzeigen",
    makeColorsStronger: "Farben stärker machen",
    colorsAdjusted: "Farben wurden angepasst",
    makeTextEasierToSee: "Macht Text mit stärkeren Farben leichter zu sehen",
    increaseContrastDesc: "Erhöht den Kontrast zwischen Text und Hintergrund für bessere Sichtbarkeit",
    helpForScreenReaders: "Hilfe für Bildschirmleser",
    interfaceAdjustedForScreenReaders: "Benutzeroberfläche für Bildschirmleser angepasst",
    worksWithScreenReaderSoftware: "Lässt die App besser mit Bildschirmleser-Software funktionieren",
    optimizesInterfaceElements: "Optimiert Benutzeroberflächenelemente und fügt zusätzlichen Kontext für Bildschirmleser hinzu",
    makeAppEasierToUse: "Die App für Sie einfacher zu verwenden machen",
    customizeAccessibilityNeeds: "Passen Sie die App an Ihre Barrierefreiheitsbedürfnisse an",
    easyWordsBasicOptions: "Einfache Wörter und Grundoptionen",
    moreOptionsTechnicalWords: "Mehr Optionen und technische Wörter",
    textSizeOptions: "Textgrößenoptionen",
    fontSizeOptions: "Schriftgrößenoptionen",
    makeText: "Text machen",
    setFontSizeTo: "Schriftgröße einstellen auf",
    languageOptions: "Sprachoptionen",
    languageSelection: "Sprachauswahl",
    changeLanguageTo: "Sprache ändern zu",
    setLanguageTo: "Sprache einstellen auf",
    goTo: "Gehen zu",
    quickAccessTips: "Schnellzugriff-Tipps",
    navigateBetweenElements: "Zwischen Elementen navigieren",
    activateButtons: "Schaltflächen aktivieren",
    closeDialogsReturn: "Dialoge schließen oder zum vorherigen Bereich zurückkehren",
    increaseBrowserZoom: "Browser-Zoom erhöhen",
    textSizeChanged: "Textgröße geändert",
    textIsNow: "Text ist jetzt",
    fontSizeUpdated: "Schriftgröße Aktualisiert",
    fontSizeChangedTo: "Schriftgröße geändert zu",
    colorsBackToNormal: "Farben zurück zur Normalität",
    highContrastOn: "Hoher Kontrast an",
    highContrastDisabled: "Hoher Kontrast Deaktiviert",
    highContrastEnabled: "Hoher Kontrast Aktiviert",
    visualContrastAdjusted: "Visueller Kontrast wurde angepasst",
    screenReaderHelpOff: "Bildschirmleser-Hilfe aus",
    screenReaderHelpOn: "Bildschirmleser-Hilfe an",
    screenReaderModeDisabled: "Bildschirmleser-Modus Deaktiviert",
    screenReaderModeEnabled: "Bildschirmleser-Modus Aktiviert",
    interfaceOptimizedForScreenReaders: "Benutzeroberfläche für Bildschirmleser optimiert",
    simpleModeOn: "Einfacher Modus an",
    detailedModeOn: "Detaillierter Modus an",
    usingSimpleLanguage: "Verwende einfache Sprache und Grundoptionen",
    showingAdvancedOptions: "Zeige erweiterte Optionen und technische Begriffe",
    financialHealthAssessment: "Finanzielle Gesundheitsbewertung",
    financialHealthDescription: "Geben Sie Ihre finanziellen Informationen ein, um eine personalisierte Gesundheitsbewertung und Empfehlungen zu erhalten",
    monthlyIncome: "Monatliches Einkommen ($)",
    monthlyExpenses: "Monatliche Ausgaben ($)",
    totalSavings: "Gesamtersparnisse ($)",
    totalDebt: "Gesamtschulden ($)",
    emergencyFund: "Notfallfonds ($)",
    calculateScore: "Meine Finanzielle Gesundheitsbewertung Berechnen",
    yourScore: "Ihre Finanzielle Gesundheitsbewertung",
    excellent: "Ausgezeichnet",
    good: "Gut",
    fair: "Angemessen",
    needsImprovement: "Verbesserung Erforderlich",
    savingsRate: "Sparquote",
    emergencyMonths: "Notfall-Monate",
    debtToIncome: "Schulden zu Einkommen",
    recommendations: "Personalisierte Empfehlungen:",
    additionalTips: "Zusätzliche Tipps:",
    wasHelpful: "War dieser Rat hilfreich?",
    helpful: "Hilfreich",
    notHelpful: "Nicht Hilfreich",
    getAIHelp: "KI-Hilfe Erhalten",
    tutorialWelcome: "Willkommen bei Der Richtige Spender!",
    tutorialWelcomeDesc: "Diese App hilft Ihnen, Ihr Geld besser zu verwalten. Lassen Sie uns einen kurzen Rundgang machen, um Ihnen zu zeigen, wie alles funktioniert.",
    tutorialAssessment: "Finanzielle Gesundheitsbewertung",
    tutorialAssessmentDesc: "Beginnen Sie hier, um zu überprüfen, wie Sie mit Geld umgehen. Sie erhalten eine Bewertung und personalisierte Ratschläge zur Verbesserung Ihrer Finanzen.",
    tutorialBudget: "Budget-Helfer",
    tutorialBudgetDesc: "Erstellen Sie einen Budgetplan, der für Ihr Einkommen funktioniert. Die App wird die beste Budgetregel für Ihre Situation vorschlagen.",
    tutorialAI: "KI-Geld-Helfer",
    tutorialAIDesc: "Stellen Sie Fragen und erhalten Sie sofortige Hilfe bei Geldentscheidungen. Es ist wie ein Finanzberater, der rund um die Uhr verfügbar ist.",
    tutorialAccessibility: "Barrierefreiheits-Einstellungen",
    tutorialAccessibilityDesc: "Lassen Sie die App besser für Sie funktionieren. Ändern Sie Textgröße, Farben, Sprache und mehr, um Ihren Bedürfnissen zu entsprechen.",
    tutorialReady: "Bereit zum Starten!",
    tutorialReadyDesc: "Wir empfehlen, mit der Finanziellen Gesundheitsbewertung zu beginnen, um Ihre aktuelle Situation zu verstehen und personalisierte Ratschläge zu erhalten.",
    appTutorial: "App-Tutorial",
    skipTutorial: "Tutorial Überspringen",
    previous: "Vorherige",
    next: "Nächste",
    startAssessment: "Bewertung Starten",
    exploreMyOwn: "Selbst Erkunden",
    back: "Zurück",
    backToOverview: "Zurück zur Übersicht",
    start: "Starten",
    getStarted: "Loslegen",
    didYouKnow: "Wussten Sie?",
    showAnotherFact: "Einen Anderen Fakt Zeigen",
    skipToMain: "Zum Hauptinhalt springen",
    checkMoneyHealth: "Ihre Geld-Gesundheit Prüfen",
    checkMoneyHealthDesc: "Sehen Sie, wie Sie mit Geld umgehen und erhalten Sie Hilfe",
    budgetHelper: "Budget-Helfer",
    budgetHelperDesc: "Erstellen Sie einen Plan für Ihr Geld, der für Sie funktioniert",
    moneyHelperChat: "Geld-Helfer-Chat",
    moneyHelperChatDesc: "Stellen Sie Fragen und erhalten Sie Hilfe bei Geldentscheidungen",
    makeAppEasier: "App Einfacher zu Verwenden Machen",
    makeAppEasierDesc: "Ändern Sie, wie die App aussieht und für Sie funktioniert",
    invalidInput: "Ungültige Eingabe",
    enterValidIncome: "Bitte geben Sie ein gültiges monatliches Einkommen ein",
    assessmentComplete: "Bewertung Abgeschlossen!",
    scoreMessage: "Ihre finanzielle Gesundheitsbewertung ist",
    thankYou: "Danke!",
    adviceHelpful: "Wir freuen uns, dass der Rat hilfreich war",
    moreAdvice: "Weitere Ratschläge kommen!",
    additionalTipsDesc: "Hier sind zusätzliche Tipps, die helfen könnten",
    aiHelper: "KI-Helfer",
    navigateToAI: "Navigieren Sie zum KI-Chat-Bereich für personalisierte Unterstützung"
  },
  it: {
    appTitle: "Il Spendaccione Corretto",
    appSubtitle: "Il tuo compagno accessibile per il benessere finanziario",
    welcomeTitle: "Prendi il Controllo del Tuo Futuro Finanziario",
    welcomeDescription: "Che tu sia nuovo nella gestione del denaro o stia cercando di migliorare la tua salute finanziaria, siamo qui per aiutarti a prendere decisioni informate senza bisogno di consulenti costosi.",
    selectLanguage: "Seleziona Lingua",
    languageDescription: "Scegli la tua lingua preferita per continuare",
    continue: "Continua",
    accessibilitySettings: "Impostazioni di Accessibilità",
    textSize: "Dimensione del Testo",
    visualAccessibility: "Accessibilità Visiva",
    screenReaderSupport: "Supporto per Lettore di Schermo",
    language: "Lingua",
    interfaceMode: "Modalità Interfaccia",
    simple: "Semplice",
    detailed: "Dettagliato",
    small: "Piccolo",
    medium: "Medio",
    large: "Grande",
    extraLarge: "Extra Grande",
    highContrastMode: "Modalità Alto Contrasto",
    enhancedScreenReaderMode: "Modalità Lettore di Schermo Migliorata",
    simpleMode: "Modalità Semplice",
    simpleModeDescription: "Utilizza linguaggio di base e interfaccia semplificata",
    detailedMode: "Modalità Dettagliata",
    detailedModeDescription: "Mostra opzioni avanzate e termini tecnici",
    makeColorsStronger: "Rendi i colori più forti",
    colorsAdjusted: "I colori sono stati regolati",
    makeTextEasierToSee: "Rende il testo più facile da vedere con colori più forti",
    increaseContrastDesc: "Aumenta il contrasto tra testo e sfondo per una migliore visibilità",
    helpForScreenReaders: "Aiuto per lettori di schermo",
    interfaceAdjustedForScreenReaders: "Interfaccia regolata per lettori di schermo",
    worksWithScreenReaderSoftware: "Fa funzionare meglio l'app con il software di lettura dello schermo",
    optimizesInterfaceElements: "Ottimizza gli elementi dell'interfaccia e aggiunge contesto extra per i lettori di schermo",
    makeAppEasierToUse: "Rendi l'app più facile da usare per te",
    customizeAccessibilityNeeds: "Personalizza l'app per soddisfare le tue esigenze di accessibilità",
    easyWordsBasicOptions: "Parole facili e opzioni di base",
    moreOptionsTechnicalWords: "Più opzioni e parole tecniche",
    textSizeOptions: "Opzioni dimensione testo",
    fontSizeOptions: "Opzioni dimensione carattere",
    makeText: "Rendi il testo",
    setFontSizeTo: "Imposta dimensione carattere a",
    languageOptions: "Opzioni lingua",
    languageSelection: "Selezione lingua",
    changeLanguageTo: "Cambia lingua in",
    setLanguageTo: "Imposta lingua a",
    goTo: "Vai a",
    quickAccessTips: "Suggerimenti Accesso Rapido",
    navigateBetweenElements: "Naviga tra elementi",
    activateButtons: "Attiva pulsanti",
    closeDialogsReturn: "Chiudi dialoghi o torna alla sezione precedente",
    increaseBrowserZoom: "Aumenta zoom browser",
    textSizeChanged: "Dimensione testo cambiata",
    textIsNow: "Il testo ora è",
    fontSizeUpdated: "Dimensione Carattere Aggiornata",
    fontSizeChangedTo: "Dimensione carattere cambiata a",
    colorsBackToNormal: "Colori tornati alla normalità",
    highContrastOn: "Alto contrasto attivato",
    highContrastDisabled: "Alto Contrasto Disabilitato",
    highContrastEnabled: "Alto Contrasto Abilitato",
    visualContrastAdjusted: "Contrasto visivo è stato regolato",
    screenReaderHelpOff: "Aiuto lettore di schermo spento",
    screenReaderHelpOn: "Aiuto lettore di schermo acceso",
    screenReaderModeDisabled: "Modalità Lettore di Schermo Disabilitata",
    screenReaderModeEnabled: "Modalità Lettore di Schermo Abilitata",
    interfaceOptimizedForScreenReaders: "Interfaccia ottimizzata per lettori di schermo",
    simpleModeOn: "Modalità semplice attivata",
    detailedModeOn: "Modalità dettagliata attivata",
    usingSimpleLanguage: "Utilizzando linguaggio semplice e opzioni di base",
    showingAdvancedOptions: "Mostrando opzioni avanzate e termini tecnici",
    financialHealthAssessment: "Valutazione della Salute Finanziaria",
    financialHealthDescription: "Inserisci le tue informazioni finanziarie per ottenere un punteggio personalizzato e raccomandazioni",
    monthlyIncome: "Reddito Mensile ($)",
    monthlyExpenses: "Spese Mensili ($)",
    totalSavings: "Risparmi Totali ($)",
    totalDebt: "Debito Totale ($)",
    emergencyFund: "Fondo di Emergenza ($)",
    calculateScore: "Calcola il Mio Punteggio di Salute Finanziaria",
    yourScore: "Il Tuo Punteggio di Salute Finanziaria",
    excellent: "Eccellente",
    good: "Buono",
    fair: "Discreto",
    needsImprovement: "Necessita Miglioramento",
    savingsRate: "Tasso di Risparmio",
    emergencyMonths: "Mesi di Emergenza",
    debtToIncome: "Debito su Reddito",
    recommendations: "Raccomandazioni Personalizzate:",
    additionalTips: "Suggerimenti Aggiuntivi:",
    wasHelpful: "Questo consiglio è stato utile?",
    helpful: "Utile",
    notHelpful: "Non Utile",
    getAIHelp: "Ottieni Aiuto IA",
    tutorialWelcome: "Benvenuto su Il Spendaccione Corretto!",
    tutorialWelcomeDesc: "Questa app ti aiuta a gestire meglio i tuoi soldi. Facciamo un tour veloce per mostrarti come funziona tutto.",
    tutorialAssessment: "Valutazione della Salute Finanziaria",
    tutorialAssessmentDesc: "Inizia qui per controllare come te la cavi con i soldi. Otterrai un punteggio e consigli personalizzati per migliorare le tue finanze.",
    tutorialBudget: "Assistente Budget",
    tutorialBudgetDesc: "Crea un piano budget che funziona per il tuo reddito. L'app suggerirà la migliore regola di budget per la tua situazione.",
    tutorialAI: "Assistente Soldi IA",
    tutorialAIDesc: "Fai domande e ottieni aiuto istantaneo con le decisioni sui soldi. È come avere un consulente finanziario disponibile 24/7.",
    tutorialAccessibility: "Impostazioni di Accessibilità",
    tutorialAccessibilityDesc: "Fa funzionare meglio l'app per te. Cambia dimensione testo, colori, lingua e altro per soddisfare le tue esigenze.",
    tutorialReady: "Pronto per Iniziare!",
    tutorialReadyDesc: "Raccomandiamo di iniziare con la Valutazione della Salute Finanziaria per capire la tua situazione attuale e ottenere consigli personalizzati.",
    appTutorial: "Tutorial dell'App",
    skipTutorial: "Salta Tutorial",
    previous: "Precedente",
    next: "Successivo",
    startAssessment: "Inizia Valutazione",
    exploreMyOwn: "Esplora da Solo",
    back: "Indietro",
    backToOverview: "Torna alla Panoramica",
    start: "Inizia",
    getStarted: "Iniziare",
    didYouKnow: "Lo Sapevi?",
    showAnotherFact: "Mostra Un Altro Fatto",
    skipToMain: "Vai al contenuto principale",
    checkMoneyHealth: "Controlla la Salute dei Tuoi Soldi",
    checkMoneyHealthDesc: "Vedi come te la cavi con i soldi e ottieni aiuto",
    budgetHelper: "Assistente Budget",
    budgetHelperDesc: "Fai un piano per i tuoi soldi che funziona per te",
    moneyHelperChat: "Chat Assistente Soldi",
    moneyHelperChatDesc: "Fai domande e ottieni aiuto con le decisioni sui soldi",
    makeAppEasier: "Rendi l'App Più Facile da Usare",
    makeAppEasierDesc: "Cambia come appare e funziona l'app per te",
    invalidInput: "Input Non Valido",
    enterValidIncome: "Per favore inserisci un reddito mensile valido",
    assessmentComplete: "Valutazione Completata!",
    scoreMessage: "Il tuo punteggio di salute finanziaria è",
    thankYou: "Grazie!",
    adviceHelpful: "Siamo contenti che il consiglio sia stato utile",
    moreAdvice: "Altri consigli in arrivo!",
    additionalTipsDesc: "Ecco suggerimenti aggiuntivi che potrebbero aiutare",
    aiHelper: "Assistente IA",
    navigateToAI: "Naviga alla sezione Chat IA per assistenza personalizzata"
  },
  pt: {
    appTitle: "O Gastador Correto",
    appSubtitle: "Seu companheiro acessível de bem-estar financeiro",
    welcomeTitle: "Assuma o Controle do Seu Futuro Financeiro",
    welcomeDescription: "Seja você novo no gerenciamento de dinheiro ou procurando melhorar sua saúde financeira, estamos aqui para ajudá-lo a tomar decisões informadas sem a necessidade de consultores caros.",
    selectLanguage: "Selecionar Idioma",
    languageDescription: "Escolha seu idioma preferido para continuar",
    continue: "Continuar",
    accessibilitySettings: "Configurações de Acessibilidade",
    textSize: "Tamanho do Texto",
    visualAccessibility: "Acessibilidade Visual",
    screenReaderSupport: "Suporte para Leitor de Tela",
    language: "Idioma",
    interfaceMode: "Modo da Interface",
    simple: "Simples",
    detailed: "Detalhado",
    small: "Pequeno",
    medium: "Médio",
    large: "Grande",
    extraLarge: "Extra Grande",
    highContrastMode: "Modo Alto Contraste",
    enhancedScreenReaderMode: "Modo Aprimorado de Leitor de Tela",
    simpleMode: "Modo Simples",
    simpleModeDescription: "Usar linguagem básica e interface simplificada",
    detailedMode: "Modo Detalhado",
    detailedModeDescription: "Mostrar opções avançadas e termos técnicos",
    makeColorsStronger: "Tornar as cores mais fortes",
    colorsAdjusted: "As cores foram ajustadas",
    makeTextEasierToSee: "Torna o texto mais fácil de ver com cores mais fortes",
    increaseContrastDesc: "Aumenta o contraste entre texto e fundo para melhor visibilidade",
    helpForScreenReaders: "Ajuda para leitores de tela",
    interfaceAdjustedForScreenReaders: "Interface ajustada para leitores de tela",
    worksWithScreenReaderSoftware: "Faz o app funcionar melhor com software de leitura de tela",
    optimizesInterfaceElements: "Otimiza elementos da interface e adiciona contexto extra para leitores de tela",
    makeAppEasierToUse: "Tornar o app mais fácil de usar para você",
    customizeAccessibilityNeeds: "Personalize o app para atender suas necessidades de acessibilidade",
    easyWordsBasicOptions: "Palavras fáceis e opções básicas",
    moreOptionsTechnicalWords: "Mais opções e palavras técnicas",
    textSizeOptions: "Opções de tamanho de texto",
    fontSizeOptions: "Opções de tamanho de fonte",
    makeText: "Tornar texto",
    setFontSizeTo: "Definir tamanho da fonte para",
    languageOptions: "Opções de idioma",
    languageSelection: "Seleção de idioma",
    changeLanguageTo: "Mudar idioma para",
    setLanguageTo: "Definir idioma para",
    goTo: "Ir para",
    quickAccessTips: "Dicas de Acesso Rápido",
    navigateBetweenElements: "Navegar entre elementos",
    activateButtons: "Ativar botões",
    closeDialogsReturn: "Fechar diálogos ou retornar à seção anterior",
    increaseBrowserZoom: "Aumentar zoom do navegador",
    textSizeChanged: "Tamanho do texto alterado",
    textIsNow: "O texto agora é",
    fontSizeUpdated: "Tamanho da Fonte Atualizado",
    fontSizeChangedTo: "Tamanho da fonte alterado para",
    colorsBackToNormal: "Cores de volta ao normal",
    highContrastOn: "Alto contraste ligado",
    highContrastDisabled: "Alto Contraste Desabilitado",
    highContrastEnabled: "Alto Contraste Habilitado",
    visualContrastAdjusted: "Contraste visual foi ajustado",
    screenReaderHelpOff: "Ajuda do leitor de tela desligada",
    screenReaderHelpOn: "Ajuda do leitor de tela ligada",
    screenReaderModeDisabled: "Modo Leitor de Tela Desabilitado",
    screenReaderModeEnabled: "Modo Leitor de Tela Habilitado",
    interfaceOptimizedForScreenReaders: "Interface otimizada para leitores de tela",
    simpleModeOn: "Modo simples ligado",
    detailedModeOn: "Modo detalhado ligado",
    usingSimpleLanguage: "Usando linguagem simples e opções básicas",
    showingAdvancedOptions: "Mostrando opções avançadas e termos técnicos",
    financialHealthAssessment: "Avaliação da Saúde Financeira",
    financialHealthDescription: "Digite suas informações financeiras para obter uma pontuação personalizada e recomendações",
    monthlyIncome: "Renda Mensal ($)",
    monthlyExpenses: "Gastos Mensais ($)",
    totalSavings: "Poupança Total ($)",
    totalDebt: "Dívida Total ($)",
    emergencyFund: "Fundo de Emergência ($)",
    calculateScore: "Calcular Minha Pontuação de Saúde Financeira",
    yourScore: "Sua Pontuação de Saúde Financeira",
    excellent: "Excelente",
    good: "Bom",
    fair: "Razoável",
    needsImprovement: "Precisa de Melhoria",
    savingsRate: "Taxa de Poupança",
    emergencyMonths: "Meses de Emergência",
    debtToIncome: "Dívida sobre Renda",
    recommendations: "Recomendações Personalizadas:",
    additionalTips: "Dicas Adicionais:",
    wasHelpful: "Este conselho foi útil?",
    helpful: "Útil",
    notHelpful: "Não Útil",
    getAIHelp: "Obter Ajuda da IA",
    tutorialWelcome: "Bem-vindo ao O Gastador Correto!",
    tutorialWelcomeDesc: "Este app ajuda você a gerenciar melhor seu dinheiro. Vamos fazer um tour rápido para mostrar como tudo funciona.",
    tutorialAssessment: "Avaliação da Saúde Financeira",
    tutorialAssessmentDesc: "Comece aqui para verificar como você está indo com dinheiro. Você receberá uma pontuação e conselhos personalizados para melhorar suas finanças.",
    tutorialBudget: "Assistente de Orçamento",
    tutorialBudgetDesc: "Crie um plano de orçamento que funciona para sua renda. O app sugerirá a melhor regra de orçamento para sua situação.",
    tutorialAI: "Assistente de Dinheiro IA",
    tutorialAIDesc: "Faça perguntas e obtenha ajuda instantânea com decisões de dinheiro. É como ter um consultor financeiro disponível 24/7.",
    tutorialAccessibility: "Configurações de Acessibilidade",
    tutorialAccessibilityDesc: "Faça o app funcionar melhor para você. Mude tamanho do texto, cores, idioma e mais para atender suas necessidades.",
    tutorialReady: "Pronto para Começar!",
    tutorialReadyDesc: "Recomendamos começar com a Avaliação da Saúde Financeira para entender sua situação atual e obter conselhos personalizados.",
    appTutorial: "Tutorial do App",
    skipTutorial: "Pular Tutorial",
    previous: "Anterior",
    next: "Próximo",
    startAssessment: "Iniciar Avaliação",
    exploreMyOwn: "Explorar por Conta Própria",
    back: "Voltar",
    backToOverview: "Voltar ao Resumo",
    start: "Começar",
    getStarted: "Começar",
    didYouKnow: "Você Sabia?",
    showAnotherFact: "Mostrar Outro Fato",
    skipToMain: "Ir para conteúdo principal",
    checkMoneyHealth: "Verificar Saúde do Seu Dinheiro",
    checkMoneyHealthDesc: "Veja como você está indo com dinheiro e obtenha ajuda",
    budgetHelper: "Assistente de Orçamento",
    budgetHelperDesc: "Faça um plano para seu dinheiro que funciona para você",
    moneyHelperChat: "Chat Assistente de Dinheiro",
    moneyHelperChatDesc: "Faça perguntas e obtenha ajuda com decisões de dinheiro",
    makeAppEasier: "Tornar o App Mais Fácil de Usar",
    makeAppEasierDesc: "Mude como o app aparece e funciona para você",
    invalidInput: "Entrada Inválida",
    enterValidIncome: "Por favor digite uma renda mensal válida",
    assessmentComplete: "Avaliação Completa!",
    scoreMessage: "Sua pontuação de saúde financeira é",
    thankYou: "Obrigado!",
    adviceHelpful: "Ficamos felizes que o conselho foi útil",
    moreAdvice: "Mais conselhos chegando!",
    additionalTipsDesc: "Aqui estão dicas adicionais que podem ajudar",
    aiHelper: "Assistente IA",
    navigateToAI: "Navegue para a seção Chat IA para assistência personalizada"
  },
  ru: {
    appTitle: "Правильный Тратитель",
    appSubtitle: "Ваш доступный спутник финансового благополучия",
    welcomeTitle: "Возьмите Контроль над Своим Финансовым Будущим",
    welcomeDescription: "Будь вы новичком в управлении деньгами или стремитесь улучшить свое финансовое здоровье, мы здесь, чтобы помочь вам принимать обоснованные решения без необходимости дорогих консультантов.",
    selectLanguage: "Выбрать Язык",
    languageDescription: "Выберите предпочитаемый язык для продолжения",
    continue: "Продолжить",
    accessibilitySettings: "Настройки Доступности",
    textSize: "Размер Текста",
    visualAccessibility: "Визуальная Доступность",
    screenReaderSupport: "Поддержка Экранного Чтеца",
    language: "Язык",
    interfaceMode: "Режим Интерфейса",
    simple: "Простой",
    detailed: "Подробный",
    small: "Маленький",
    medium: "Средний",
    large: "Большой",
    extraLarge: "Очень Большой",
    highContrastMode: "Режим Высокого Контраста",
    enhancedScreenReaderMode: "Улучшенный Режим Экранного Чтеца",
    simpleMode: "Простой Режим",
    simpleModeDescription: "Использовать простой язык и упрощенный интерфейс",
    detailedMode: "Подробный Режим",
    detailedModeDescription: "Показывать расширенные опции и технические термины",
    makeColorsStronger: "Сделать цвета ярче",
    colorsAdjusted: "Цвета были настроены",
    makeTextEasierToSee: "Делает текст легче для чтения с более яркими цветами",
    increaseContrastDesc: "Увеличивает контрастность между текстом и фоном для лучшей видимости",
    helpForScreenReaders: "Помощь для экранных чтецов",
    interfaceAdjustedForScreenReaders: "Интерфейс настроен для экранных чтецов",
    worksWithScreenReaderSoftware: "Делает приложение лучше совместимым с программами чтения экрана",
    optimizesInterfaceElements: "Оптимизирует элементы интерфейса и добавляет дополнительный контекст для экранных чтецов",
    makeAppEasierToUse: "Сделать приложение проще в использовании для вас",
    customizeAccessibilityNeeds: "Настройте приложение под ваши потребности доступности",
    easyWordsBasicOptions: "Простые слова и базовые опции",
    moreOptionsTechnicalWords: "Больше опций и технических слов",
    textSizeOptions: "Опции размера текста",
    fontSizeOptions: "Опции размера шрифта",
    makeText: "Сделать текст",
    setFontSizeTo: "Установить размер шрифта на",
    languageOptions: "Опции языка",
    languageSelection: "Выбор языка",
    changeLanguageTo: "Изменить язык на",
    setLanguageTo: "Установить язык на",
    goTo: "Перейти к",
    quickAccessTips: "Советы Быстрого Доступа",
    navigateBetweenElements: "Навигация между элементами",
    activateButtons: "Активировать кнопки",
    closeDialogsReturn: "Закрыть диалоги или вернуться к предыдущему разделу",
    increaseBrowserZoom: "Увеличить масштаб браузера",
    textSizeChanged: "Размер текста изменен",
    textIsNow: "Текст теперь",
    fontSizeUpdated: "Размер Шрифта Обновлен",
    fontSizeChangedTo: "Размер шрифта изменен на",
    colorsBackToNormal: "Цвета вернулись к нормальным",
    highContrastOn: "Высокий контраст включен",
    highContrastDisabled: "Высокий Контраст Отключен",
    highContrastEnabled: "Высокий Контраст Включен",
    visualContrastAdjusted: "Визуальный контраст был настроен",
    screenReaderHelpOff: "Помощь экранного чтеца выключена",
    screenReaderHelpOn: "Помощь экранного чтеца включена",
    screenReaderModeDisabled: "Режим Экранного Чтеца Отключен",
    screenReaderModeEnabled: "Режим Экранного Чтеца Включен",
    interfaceOptimizedForScreenReaders: "Интерфейс оптимизирован для экранных чтецов",
    simpleModeOn: "Простой режим включен",
    detailedModeOn: "Подробный режим включен",
    usingSimpleLanguage: "Использование простого языка и базовых опций",
    showingAdvancedOptions: "Показ расширенных опций и технических терминов",
    financialHealthAssessment: "Оценка Финансового Здоровья",
    financialHealthDescription: "Введите свою финансовую информацию, чтобы получить персонализированную оценку и рекомендации",
    monthlyIncome: "Ежемесячный Доход ($)",
    monthlyExpenses: "Ежемесячные Расходы ($)",
    totalSavings: "Общие Сбережения ($)",
    totalDebt: "Общий Долг ($)",
    emergencyFund: "Резервный Фонд ($)",
    calculateScore: "Рассчитать Мою Оценку Финансового Здоровья",
    yourScore: "Ваша Оценка Финансового Здоровья",
    excellent: "Отлично",
    good: "Хорошо",
    fair: "Удовлетворительно",
    needsImprovement: "Требует Улучшения",
    savingsRate: "Норма Сбережений",
    emergencyMonths: "Месяцы Резерва",
    debtToIncome: "Долг к Доходу",
    recommendations: "Персонализированные Рекомендации:",
    additionalTips: "Дополнительные Советы:",
    wasHelpful: "Был ли этот совет полезен?",
    helpful: "Полезно",
    notHelpful: "Не Полезно",
    getAIHelp: "Получить Помощь ИИ",
    tutorialWelcome: "Добро пожаловать в Правильный Тратитель!",
    tutorialWelcomeDesc: "Это приложение помогает вам лучше управлять своими деньгами. Давайте сделаем быстрый обзор, чтобы показать, как все работает.",
    tutorialAssessment: "Оценка Финансового Здоровья",
    tutorialAssessmentDesc: "Начните здесь, чтобы проверить, как у вас дела с деньгами. Вы получите оценку и персональные советы для улучшения ваших финансов.",
    tutorialBudget: "Помощник по Бюджету",
    tutorialBudgetDesc: "Создайте план бюджета, который работает для вашего дохода. Приложение предложит лучшее правило бюджета для вашей ситуации.",
    tutorialAI: "ИИ Помощник по Деньгам",
    tutorialAIDesc: "Задавайте вопросы и получайте мгновенную помощь с денежными решениями. Это как иметь финансового консультанта доступного 24/7.",
    tutorialAccessibility: "Настройки Доступности",
    tutorialAccessibilityDesc: "Сделайте приложение лучше работающим для вас. Измените размер текста, цвета, язык и многое другое для ваших потребностей.",
    tutorialReady: "Готовы Начать!",
    tutorialReadyDesc: "Мы рекомендуем начать с Оценки Финансового Здоровья, чтобы понять вашу текущую ситуацию и получить персональные советы.",
    appTutorial: "Обучение Приложению",
    skipTutorial: "Пропустить Обучение",
    previous: "Предыдущий",
    next: "Следующий",
    startAssessment: "Начать Оценку",
    exploreMyOwn: "Исследовать Самостоятельно",
    back: "Назад",
    backToOverview: "Вернуться к Обзору",
    start: "Начать",
    getStarted: "Начать",
    didYouKnow: "Знали ли Вы?",
    showAnotherFact: "Показать Другой Факт",
    skipToMain: "Перейти к основному содержанию",
    checkMoneyHealth: "Проверить Здоровье Ваших Денег",
    checkMoneyHealthDesc: "Посмотрите, как у вас дела с деньгами и получите помощь",
    budgetHelper: "Помощник по Бюджету",
    budgetHelperDesc: "Составьте план для ваших денег, который работает для вас",
    moneyHelperChat: "Чат Помощник по Деньгам",
    moneyHelperChatDesc: "Задавайте вопросы и получайте помощь с денежными решениями",
    makeAppEasier: "Сделать Приложение Проще в Использовании",
    makeAppEasierDesc: "Измените, как приложение выглядит и работает для вас",
    invalidInput: "Неверный Ввод",
    enterValidIncome: "Пожалуйста, введите действительный ежемесячный доход",
    assessmentComplete: "Оценка Завершена!",
    scoreMessage: "Ваша оценка финансового здоровья",
    thankYou: "Спасибо!",
    adviceHelpful: "Мы рады, что совет был полезен",
    moreAdvice: "Больше советов приближается!",
    additionalTipsDesc: "Вот дополнительные советы, которые могут помочь",
    aiHelper: "ИИ Помощник",
    navigateToAI: "Перейдите в раздел ИИ Чат для персонализированной помощи"
  },
  ja: {
    appTitle: "正しい支出者",
    appSubtitle: "あなたのアクセシブルな財務健康コンパニオン",
    welcomeTitle: "あなたの金融の未来をコントロールしよう",
    welcomeDescription: "お金の管理が初めてでも、財務健康の改善を目指していても、高額なアドバイザーなしで十分な情報に基づいた決定を下すお手伝いをします。",
    selectLanguage: "言語を選択",
    languageDescription: "続行するためにお好みの言語を選択してください",
    continue: "続行",
    accessibilitySettings: "アクセシビリティ設定",
    textSize: "テキストサイズ",
    visualAccessibility: "視覚的アクセシビリティ",
    screenReaderSupport: "スクリーンリーダーサポート",
    language: "言語",
    interfaceMode: "インターフェースモード",
    simple: "シンプル",
    detailed: "詳細",
    small: "小",
    medium: "中",
    large: "大",
    extraLarge: "特大",
    highContrastMode: "ハイコントラストモード",
    enhancedScreenReaderMode: "拡張スクリーンリーダーモード",
    simpleMode: "シンプルモード",
    simpleModeDescription: "基本的な言語と簡素化されたインターフェースを使用",
    detailedMode: "詳細モード",
    detailedModeDescription: "高度なオプションと技術用語を表示",
    makeColorsStronger: "色を強くする",
    colorsAdjusted: "色が調整されました",
    makeTextEasierToSee: "より強い色でテキストを見やすくします",
    increaseContrastDesc: "より良い視認性のためにテキストと背景のコントラストを増加させます",
    helpForScreenReaders: "スクリーンリーダーのヘルプ",
    interfaceAdjustedForScreenReaders: "スクリーンリーダー用にインターフェースが調整されました",
    worksWithScreenReaderSoftware: "スクリーンリーダーソフトウェアでアプリをより良く動作させます",
    optimizesInterfaceElements: "インターフェース要素を最適化し、スクリーンリーダーに追加のコンテキストを提供します",
    makeAppEasierToUse: "アプリをあなたにとって使いやすくする",
    customizeAccessibilityNeeds: "あなたのアクセシビリティニーズに合わせてアプリをカスタマイズ",
    easyWordsBasicOptions: "簡単な言葉と基本オプション",
    moreOptionsTechnicalWords: "より多くのオプションと技術用語",
    textSizeOptions: "テキストサイズオプション",
    fontSizeOptions: "フォントサイズオプション",
    makeText: "テキストを",
    setFontSizeTo: "フォントサイズを設定",
    languageOptions: "言語オプション",
    languageSelection: "言語選択",
    changeLanguageTo: "言語を変更",
    setLanguageTo: "言語を設定",
    goTo: "に行く",
    quickAccessTips: "クイックアクセスのヒント",
    navigateBetweenElements: "要素間をナビゲート",
    activateButtons: "ボタンを活性化",
    closeDialogsReturn: "ダイアログを閉じるか前のセクションに戻る",
    increaseBrowserZoom: "ブラウザのズームを増加",
    textSizeChanged: "テキストサイズが変更されました",
    textIsNow: "テキストは今",
    fontSizeUpdated: "フォントサイズが更新されました",
    fontSizeChangedTo: "フォントサイズが変更されました",
    colorsBackToNormal: "色が通常に戻りました",
    highContrastOn: "ハイコントラストがオン",
    highContrastDisabled: "ハイコントラストが無効",
    highContrastEnabled: "ハイコントラストが有効",
    visualContrastAdjusted: "視覚的コントラストが調整されました",
    screenReaderHelpOff: "スクリーンリーダーヘルプがオフ",
    screenReaderHelpOn: "スクリーンリーダーヘルプがオン",
    screenReaderModeDisabled: "スクリーンリーダーモードが無効",
    screenReaderModeEnabled: "スクリーンリーダーモードが有効",
    interfaceOptimizedForScreenReaders: "スクリーンリーダー用にインターフェースが最適化されました",
    simpleModeOn: "シンプルモードがオン",
    detailedModeOn: "詳細モードがオン",
    usingSimpleLanguage: "簡単な言語と基本オプションを使用",
    showingAdvancedOptions: "高度なオプションと技術用語を表示",
    financialHealthAssessment: "財務健康評価",
    financialHealthDescription: "パーソナライズされたスコアと推奨事項を取得するために財務情報を入力してください",
    monthlyIncome: "月収 ($)",
    monthlyExpenses: "月の支出 ($)",
    totalSavings: "総貯蓄 ($)",
    totalDebt: "総負債 ($)",
    emergencyFund: "緊急資金 ($)",
    calculateScore: "私の財務健康スコアを計算",
    yourScore: "あなたの財務健康スコア",
    excellent: "優秀",
    good: "良好",
    fair: "まあまあ",
    needsImprovement: "改善が必要",
    savingsRate: "貯蓄率",
    emergencyMonths: "緊急時の月数",
    debtToIncome: "負債対収入",
    recommendations: "パーソナライズされた推奨事項:",
    additionalTips: "追加のヒント:",
    wasHelpful: "このアドバイスは役に立ちましたか？",
    helpful: "役に立った",
    notHelpful: "役に立たなかった",
    getAIHelp: "AIヘルプを取得",
    tutorialWelcome: "正しい支出者へようこそ！",
    tutorialWelcomeDesc: "このアプリはあなたのお金をより良く管理するのに役立ちます。すべてがどのように機能するかを示すために、クイックツアーをしましょう。",
    tutorialAssessment: "財務健康評価",
    tutorialAssessmentDesc: "お金についてどうしているかをチェックするためにここから始めてください。あなたの財務を改善するためのスコアとパーソナライズされたアドバイスを取得します。",
    tutorialBudget: "予算ヘルパー",
    tutorialBudgetDesc: "あなたの収入に合った予算プランを作成してください。アプリはあなたの状況に最適な予算ルールを提案します。",
    tutorialAI: "AIマネーヘルパー",
    tutorialAIDesc: "質問をして、お金の決定について即座にヘルプを取得してください。24時間365日利用可能な金融アドバイザーを持っているようなものです。",
    tutorialAccessibility: "アクセシビリティ設定",
    tutorialAccessibilityDesc: "アプリをあなたにとってより良く動作させてください。あなたのニーズに合わせてテキストサイズ、色、言語などを変更してください。",
    tutorialReady: "開始する準備ができました！",
    tutorialReadyDesc: "現在の状況を理解し、パーソナライズされたアドバイスを取得するために財務健康評価から始めることをお勧めします。",
    appTutorial: "アプリチュートリアル",
    skipTutorial: "チュートリアルをスキップ",
    previous: "前",
    next: "次",
    startAssessment: "評価を開始",
    exploreMyOwn: "自分で探索",
    back: "戻る",
    backToOverview: "概要に戻る",
    start: "開始",
    getStarted: "始める",
    didYouKnow: "ご存知でしたか？",
    showAnotherFact: "別の事実を表示",
    skipToMain: "メインコンテンツにスキップ",
    checkMoneyHealth: "お金の健康をチェック",
    checkMoneyHealthDesc: "お金についてどうしているかを見て、ヘルプを取得",
    budgetHelper: "予算ヘルパー",
    budgetHelperDesc: "あなたに合ったお金のプランを作成",
    moneyHelperChat: "マネーヘルパーチャット",
    moneyHelperChatDesc: "質問をして、お金の決定についてヘルプを取得",
    makeAppEasier: "アプリを使いやすくする",
    makeAppEasierDesc: "アプリの見た目と動作をあなたに合わせて変更",
    invalidInput: "無効な入力",
    enterValidIncome: "有効な月収を入力してください",
    assessmentComplete: "評価完了！",
    scoreMessage: "あなたの財務健康スコアは",
    thankYou: "ありがとうございます！",
    adviceHelpful: "アドバイスが役に立ったことを嬉しく思います",
    moreAdvice: "より多くのアドバイスが来ています！",
    additionalTipsDesc: "役立つかもしれない追加のヒントです",
    aiHelper: "AIヘルパー",
    navigateToAI: "パーソナライズされた支援のためにAIチャットセクションにナビゲート"
  },
  ko: {
    appTitle: "올바른 지출자",
    appSubtitle: "당신의 접근 가능한 재정 건강 동반자",
    welcomeTitle: "재정 미래를 통제하세요",
    welcomeDescription: "돈 관리가 처음이든 재정 건강 개선을 원하든, 우리는 비싼 어드바이저 없이도 정보에 입각한 결정을 내리도록 도와드립니다.",
    selectLanguage: "언어 선택",
    languageDescription: "계속하려면 선호하는 언어를 선택하세요",
    continue: "계속",
    accessibilitySettings: "접근성 설정",
    textSize: "텍스트 크기",
    visualAccessibility: "시각적 접근성",
    screenReaderSupport: "스크린 리더 지원",
    language: "언어",
    interfaceMode: "인터페이스 모드",
    simple: "간단",
    detailed: "상세",
    small: "작게",
    medium: "보통",
    large: "크게",
    extraLarge: "매우 크게",
    highContrastMode: "고대비 모드",
    enhancedScreenReaderMode: "향상된 스크린 리더 모드",
    simpleMode: "간단 모드",
    simpleModeDescription: "기본 언어와 단순화된 인터페이스 사용",
    detailedMode: "상세 모드",
    detailedModeDescription: "고급 옵션과 기술 용어 표시",
    makeColorsStronger: "색상을 더 강하게",
    colorsAdjusted: "색상이 조정되었습니다",
    makeTextEasierToSee: "더 강한 색상으로 텍스트를 더 쉽게 볼 수 있게 합니다",
    increaseContrastDesc: "더 나은 가시성을 위해 텍스트와 배경 간의 대비를 증가시킵니다",
    helpForScreenReaders: "스크린 리더를 위한 도움",
    interfaceAdjustedForScreenReaders: "스크린 리더를 위해 인터페이스가 조정되었습니다",
    worksWithScreenReaderSoftware: "스크린 리더 소프트웨어와 앱이 더 잘 작동하도록 합니다",
    optimizesInterfaceElements: "인터페이스 요소를 최적화하고 스크린 리더를 위한 추가 컨텍스트를 제공합니다",
    makeAppEasierToUse: "앱을 당신에게 더 쉽게 사용할 수 있게 만들기",
    customizeAccessibilityNeeds: "접근성 요구사항에 맞게 앱을 사용자 정의하세요",
    easyWordsBasicOptions: "쉬운 단어와 기본 옵션",
    moreOptionsTechnicalWords: "더 많은 옵션과 기술 용어",
    textSizeOptions: "텍스트 크기 옵션",
    fontSizeOptions: "글꼴 크기 옵션",
    makeText: "텍스트를",
    setFontSizeTo: "글꼴 크기를 설정",
    languageOptions: "언어 옵션",
    languageSelection: "언어 선택",
    changeLanguageTo: "언어를 변경",
    setLanguageTo: "언어를 설정",
    goTo: "로 이동",
    quickAccessTips: "빠른 접근 팁",
    navigateBetweenElements: "요소 간 탐색",
    activateButtons: "버튼 활성화",
    closeDialogsReturn: "대화 상자 닫기 또는 이전 섹션으로 돌아가기",
    increaseBrowserZoom: "브라우저 확대",
    textSizeChanged: "텍스트 크기가 변경되었습니다",
    textIsNow: "텍스트가 이제",
    fontSizeUpdated: "글꼴 크기가 업데이트되었습니다",
    fontSizeChangedTo: "글꼴 크기가 변경되었습니다",
    colorsBackToNormal: "색상이 정상으로 돌아갔습니다",
    highContrastOn: "고대비가 켜짐",
    highContrastDisabled: "고대비가 비활성화됨",
    highContrastEnabled: "고대비가 활성화됨",
    visualContrastAdjusted: "시각적 대비가 조정되었습니다",
    screenReaderHelpOff: "스크린 리더 도움이 꺼짐",
    screenReaderHelpOn: "스크린 리더 도움이 켜짐",
    screenReaderModeDisabled: "스크린 리더 모드가 비활성화됨",
    screenReaderModeEnabled: "스크린 리더 모드가 활성화됨",
    interfaceOptimizedForScreenReaders: "스크린 리더를 위해 인터페이스가 최적화되었습니다",
    simpleModeOn: "간단 모드가 켜짐",
    detailedModeOn: "상세 모드가 켜짐",
    usingSimpleLanguage: "간단한 언어와 기본 옵션 사용",
    showingAdvancedOptions: "고급 옵션과 기술 용어 표시",
    financialHealthAssessment: "재정 건강 평가",
    financialHealthDescription: "개인화된 점수와 권장사항을 받기 위해 재정 정보를 입력하세요",
    monthlyIncome: "월 수입 ($)",
    monthlyExpenses: "월 지출 ($)",
    totalSavings: "총 저축 ($)",
    totalDebt: "총 부채 ($)",
    emergencyFund: "비상 자금 ($)",
    calculateScore: "내 재정 건강 점수 계산",
    yourScore: "당신의 재정 건강 점수",
    excellent: "우수",
    good: "좋음",
    fair: "보통",
    needsImprovement: "개선 필요",
    savingsRate: "저축률",
    emergencyMonths: "비상 개월",
    debtToIncome: "부채 대 소득",
    recommendations: "개인화된 권장사항:",
    additionalTips: "추가 팁:",
    wasHelpful: "이 조언이 도움이 되었나요?",
    helpful: "도움됨",
    notHelpful: "도움 안됨",
    getAIHelp: "AI 도움 받기",
    tutorialWelcome: "올바른 지출자에 오신 것을 환영합니다!",
    tutorialWelcomeDesc: "이 앱은 당신의 돈을 더 잘 관리하는 데 도움이 됩니다. 모든 것이 어떻게 작동하는지 보여주기 위해 빠른 투어를 해봅시다.",
    tutorialAssessment: "재정 건강 평가",
    tutorialAssessmentDesc: "돈에 대해 어떻게 하고 있는지 확인하기 위해 여기서 시작하세요. 당신의 재정을 개선하기 위한 점수와 개인화된 조언을 받을 것입니다.",
    tutorialBudget: "예산 도우미",
    tutorialBudgetDesc: "당신의 수입에 맞는 예산 계획을 만드세요. 앱은 당신의 상황에 가장 적합한 예산 규칙을 제안할 것입니다.",
    tutorialAI: "AI 돈 도우미",
    tutorialAIDesc: "질문하고 돈 결정에 대한 즉각적인 도움을 받으세요. 24시간 연중무휴로 이용 가능한 재정 고문을 갖는 것과 같습니다.",
    tutorialAccessibility: "접근성 설정",
    tutorialAccessibilityDesc: "앱이 당신에게 더 잘 작동하도록 만드세요. 당신의 필요에 맞게 텍스트 크기, 색상, 언어 등을 변경하세요.",
    tutorialReady: "시작할 준비가 되었습니다!",
    tutorialReadyDesc: "현재 상황을 이해하고 개인화된 조언을 받기 위해 재정 건강 평가부터 시작하는 것을 권장합니다.",
    appTutorial: "앱 튜토리얼",
    skipTutorial: "튜토리얼 건너뛰기",
    previous: "이전",
    next: "다음",
    startAssessment: "평가 시작",
    exploreMyOwn: "혼자 탐색",
    back: "뒤로",
    backToOverview: "개요로 돌아가기",
    start: "시작",
    getStarted: "시작하기",
    didYouKnow: "알고 계셨나요?",
    showAnotherFact: "다른 사실 보기",
    skipToMain: "주요 내용으로 건너뛰기",
    checkMoneyHealth: "돈 건강 확인",
    checkMoneyHealthDesc: "돈에 대해 어떻게 하고 있는지 보고 도움을 받으세요",
    budgetHelper: "예산 도우미",
    budgetHelperDesc: "당신에게 맞는 돈 계획을 만드세요",
    moneyHelperChat: "돈 도우미 채팅",
    moneyHelperChatDesc: "질문하고 돈 결정에 대한 도움을 받으세요",
    makeAppEasier: "앱을 더 쉽게 사용하기",
    makeAppEasierDesc: "앱이 어떻게 보이고 작동하는지 당신에게 맞게 변경하세요",
    invalidInput: "잘못된 입력",
    enterValidIncome: "유효한 월 수입을 입력하세요",
    assessmentComplete: "평가 완료!",
    scoreMessage: "당신의 재정 건강 점수는",
    thankYou: "감사합니다!",
    adviceHelpful: "조언이 도움이 되어서 기쁩니다",
    moreAdvice: "더 많은 조언이 나오고 있습니다!",
    additionalTipsDesc: "도움이 될 수 있는 추가 팁들입니다",
    aiHelper: "AI 도우미",
    navigateToAI: "개인화된 지원을 위해 AI 채팅 섹션으로 이동하세요"
  },
  zh: {
    appTitle: "正确的支出者",
    appSubtitle: "您的无障碍财务健康伴侣",
    welcomeTitle: "掌控您的财务未来",
    welcomeDescription: "无论您是理财新手还是希望改善财务健康，我们都在这里帮助您做出明智的决定，无需昂贵的顾问。",
    selectLanguage: "选择语言",
    languageDescription: "选择您的首选语言以继续",
    continue: "继续",
    accessibilitySettings: "无障碍设置",
    textSize: "文本大小",
    visualAccessibility: "视觉无障碍",
    screenReaderSupport: "屏幕阅读器支持",
    language: "语言",
    interfaceMode: "界面模式",
    simple: "简单",
    detailed: "详细",
    small: "小",
    medium: "中",
    large: "大",
    extraLarge: "特大",
    highContrastMode: "高对比度模式",
    enhancedScreenReaderMode: "增强屏幕阅读器模式",
    simpleMode: "简单模式",
    simpleModeDescription: "使用基本语言和简化界面",
    detailedMode: "详细模式",
    detailedModeDescription: "显示高级选项和技术术语",
    makeColorsStronger: "使颜色更强",
    colorsAdjusted: "颜色已调整",
    makeTextEasierToSee: "用更强的颜色使文本更容易看到",
    increaseContrastDesc: "增加文本和背景之间的对比度以获得更好的可见性",
    helpForScreenReaders: "屏幕阅读器帮助",
    interfaceAdjustedForScreenReaders: "已为屏幕阅读器调整界面",
    worksWithScreenReaderSoftware: "使应用与屏幕阅读器软件更好地工作",
    optimizesInterfaceElements: "优化界面元素并为屏幕阅读器添加额外上下文",
    makeAppEasierToUse: "让应用对您更容易使用",
    customizeAccessibilityNeeds: "自定义应用以满足您的无障碍需求",
    easyWordsBasicOptions: "简单词汇和基本选项",
    moreOptionsTechnicalWords: "更多选项和技术词汇",
    textSizeOptions: "文本大小选项",
    fontSizeOptions: "字体大小选项",
    makeText: "使文本",
    setFontSizeTo: "将字体大小设置为",
    languageOptions: "语言选项",
    languageSelection: "语言选择",
    changeLanguageTo: "将语言更改为",
    setLanguageTo: "将语言设置为",
    goTo: "转到",
    quickAccessTips: "快速访问提示",
    navigateBetweenElements: "在元素之间导航",
    activateButtons: "激活按钮",
    closeDialogsReturn: "关闭对话框或返回上一节",
    increaseBrowserZoom: "增加浏览器缩放",
    textSizeChanged: "文本大小已更改",
    textIsNow: "文本现在是",
    fontSizeUpdated: "字体大小已更新",
    fontSizeChangedTo: "字体大小已更改为",
    colorsBackToNormal: "颜色恢复正常",
    highContrastOn: "高对比度开启",
    highContrastDisabled: "高对比度已禁用",
    highContrastEnabled: "高对比度已启用",
    visualContrastAdjusted: "视觉对比度已调整",
    screenReaderHelpOff: "屏幕阅读器帮助关闭",
    screenReaderHelpOn: "屏幕阅读器帮助开启",
    screenReaderModeDisabled: "屏幕阅读器模式已禁用",
    screenReaderModeEnabled: "屏幕阅读器模式已启用",
    interfaceOptimizedForScreenReaders: "已为屏幕阅读器优化界面",
    simpleModeOn: "简单模式开启",
    detailedModeOn: "详细模式开启",
    usingSimpleLanguage: "使用简单语言和基本选项",
    showingAdvancedOptions: "显示高级选项和技术术语",
    financialHealthAssessment: "财务健康评估",
    financialHealthDescription: "输入您的财务信息以获得个性化评分和建议",
    monthlyIncome: "月收入 ($)",
    monthlyExpenses: "月支出 ($)",
    totalSavings: "总储蓄 ($)",
    totalDebt: "总债务 ($)",
    emergencyFund: "应急基金 ($)",
    calculateScore: "计算我的财务健康评分",
    yourScore: "您的财务健康评分",
    excellent: "优秀",
    good: "良好",
    fair: "一般",
    needsImprovement: "需要改善",
    savingsRate: "储蓄率",
    emergencyMonths: "应急月数",
    debtToIncome: "债务收入比",
    recommendations: "个性化建议：",
    additionalTips: "额外提示：",
    wasHelpful: "这个建议有用吗？",
    helpful: "有用",
    notHelpful: "无用",
    getAIHelp: "获取AI帮助",
    tutorialWelcome: "欢迎来到正确的支出者！",
    tutorialWelcomeDesc: "这个应用帮助您更好地管理您的资金。让我们快速浏览一下，向您展示一切是如何工作的。",
    tutorialAssessment: "财务健康评估",
    tutorialAssessmentDesc: "从这里开始检查您的理财情况。您将获得评分和个性化建议来改善您的财务状况。",
    tutorialBudget: "预算助手",
    tutorialBudgetDesc: "创建适合您收入的预算计划。应用将为您的情况建议最佳预算规则。",
    tutorialAI: "AI理财助手",
    tutorialAIDesc: "提问并获得关于理财决策的即时帮助。就像拥有一个24/7可用的财务顾问。",
    tutorialAccessibility: "无障碍设置",
    tutorialAccessibilityDesc: "让应用为您更好地工作。更改文本大小、颜色、语言等以满足您的需求。",
    tutorialReady: "准备开始！",
    tutorialReadyDesc: "我们建议从财务健康评估开始，以了解您的当前情况并获得个性化建议。",
    appTutorial: "应用教程",
    skipTutorial: "跳过教程",
    previous: "上一个",
    next: "下一个",
    startAssessment: "开始评估",
    exploreMyOwn: "自己探索",
    back: "返回",
    backToOverview: "返回概览",
    start: "开始",
    getStarted: "开始使用",
    didYouKnow: "您知道吗？",
    showAnotherFact: "显示另一个事实",
    skipToMain: "跳到主要内容",
    checkMoneyHealth: "检查您的资金健康",
    checkMoneyHealthDesc: "查看您的理财情况并获得帮助",
    budgetHelper: "预算助手",
    budgetHelperDesc: "为您的资金制定适合的计划",
    moneyHelperChat: "理财助手聊天",
    moneyHelperChatDesc: "提问并获得关于理财决策的帮助",
    makeAppEasier: "让应用更容易使用",
    makeAppEasierDesc: "更改应用的外观和工作方式以适合您",
    invalidInput: "无效输入",
    enterValidIncome: "请输入有效的月收入",
    assessmentComplete: "评估完成！",
    scoreMessage: "您的财务健康评分是",
    thankYou: "谢谢！",
    adviceHelpful: "我们很高兴建议对您有帮助",
    moreAdvice: "更多建议即将到来！",
    additionalTipsDesc: "以下是可能有帮助的额外提示",
    aiHelper: "AI助手",
    navigateToAI: "导航到AI聊天部分获取个性化协助"
  },
  ar: {
    appTitle: "المنفق الصحيح",
    appSubtitle: "رفيقك في الصحة المالية المتاح للجميع",
    welcomeTitle: "تحكم في مستقبلك المالي",
    welcomeDescription: "سواء كنت جديداً في إدارة الأموال أو تسعى لتحسين صحتك المالية، نحن هنا لمساعدتك على اتخاذ قرارات مدروسة دون الحاجة لمستشارين مكلفين.",
    selectLanguage: "اختر اللغة",
    languageDescription: "اختر لغتك المفضلة للمتابعة",
    continue: "متابعة",
    accessibilitySettings: "إعدادات إمكانية الوصول",
    textSize: "حجم النص",
    visualAccessibility: "إمكانية الوصول البصرية",
    screenReaderSupport: "دعم قارئ الشاشة",
    language: "اللغة",
    interfaceMode: "وضع الواجهة",
    simple: "بسيط",
    detailed: "مفصل",
    small: "صغير",
    medium: "متوسط",
    large: "كبير",
    extraLarge: "كبير جداً",
    highContrastMode: "وضع التباين العالي",
    enhancedScreenReaderMode: "وضع قارئ الشاشة المحسن",
    simpleMode: "الوضع البسيط",
    simpleModeDescription: "استخدام لغة أساسية وواجهة مبسطة",
    detailedMode: "الوضع المفصل",
    detailedModeDescription: "إظهار خيارات متقدمة ومصطلحات تقنية",
    makeColorsStronger: "جعل الألوان أقوى",
    colorsAdjusted: "تم تعديل الألوان",
    makeTextEasierToSee: "يجعل النص أسهل للرؤية بألوان أقوى",
    increaseContrastDesc: "يزيد التباين بين النص والخلفية لرؤية أفضل",
    helpForScreenReaders: "مساعدة لقارئات الشاشة",
    interfaceAdjustedForScreenReaders: "تم تعديل الواجهة لقارئات الشاشة",
    worksWithScreenReaderSoftware: "يجعل التطبيق يعمل بشكل أفضل مع برامج قراءة الشاشة",
    optimizesInterfaceElements: "يحسن عناصر الواجهة ويضيف سياقاً إضافياً لقارئات الشاشة",
    makeAppEasierToUse: "جعل التطبيق أسهل للاستخدام بالنسبة لك",
    customizeAccessibilityNeeds: "خصص التطبيق لتلبية احتياجاتك من إمكانية الوصول",
    easyWordsBasicOptions: "كلمات سهلة وخيارات أساسية",
    moreOptionsTechnicalWords: "المزيد من الخيارات والكلمات التقنية",
    textSizeOptions: "خيارات حجم النص",
    fontSizeOptions: "خيارات حجم الخط",
    makeText: "جعل النص",
    setFontSizeTo: "تعيين حجم الخط إلى",
    languageOptions: "خيارات اللغة",
    languageSelection: "اختيار اللغة",
    changeLanguageTo: "تغيير اللغة إلى",
    setLanguageTo: "تعيين اللغة إلى",
    goTo: "الذهاب إلى",
    quickAccessTips: "نصائح الوصول السريع",
    navigateBetweenElements: "التنقل بين العناصر",
    activateButtons: "تفعيل الأزرار",
    closeDialogsReturn: "إغلاق مربعات الحوار أو العودة للقسم السابق",
    increaseBrowserZoom: "زيادة تكبير المتصفح",
    textSizeChanged: "تم تغيير حجم النص",
    textIsNow: "النص الآن",
    fontSizeUpdated: "تم تحديث حجم الخط",
    fontSizeChangedTo: "تم تغيير حجم الخط إلى",
    colorsBackToNormal: "عادت الألوان إلى طبيعتها",
    highContrastOn: "تم تشغيل التباين العالي",
    highContrastDisabled: "تم تعطيل التباين العالي",
    highContrastEnabled: "تم تمكين التباين العالي",
    visualContrastAdjusted: "تم تعديل التباين البصري",
    screenReaderHelpOff: "تم إيقاف مساعدة قارئ الشاشة",
    screenReaderHelpOn: "تم تشغيل مساعدة قارئ الشاشة",
    screenReaderModeDisabled: "تم تعطيل وضع قارئ الشاشة",
    screenReaderModeEnabled: "تم تمكين وضع قارئ الشاشة",
    interfaceOptimizedForScreenReaders: "تم تحسين الواجهة لقارئات الشاشة",
    simpleModeOn: "تم تشغيل الوضع البسيط",
    detailedModeOn: "تم تشغيل الوضع المفصل",
    usingSimpleLanguage: "استخدام لغة بسيطة وخيارات أساسية",
    showingAdvancedOptions: "إظهار خيارات متقدمة ومصطلحات تقنية",
    financialHealthAssessment: "تقييم الصحة المالية",
    financialHealthDescription: "أدخل معلوماتك المالية للحصول على نقاط شخصية وتوصيات",
    monthlyIncome: "الدخل الشهري ($)",
    monthlyExpenses: "المصروفات الشهرية ($)",
    totalSavings: "إجمالي المدخرات ($)",
    totalDebt: "إجمالي الديون ($)",
    emergencyFund: "صندوق الطوارئ ($)",
    calculateScore: "احسب نقاط صحتي المالية",
    yourScore: "نقاط صحتك المالية",
    excellent: "ممتاز",
    good: "جيد",
    fair: "عادل",
    needsImprovement: "يحتاج تحسين",
    savingsRate: "معدل الادخار",
    emergencyMonths: "أشهر الطوارئ",
    debtToIncome: "الدين إلى الدخل",
    recommendations: "توصيات شخصية:",
    additionalTips: "نصائح إضافية:",
    wasHelpful: "هل كانت هذه النصيحة مفيدة؟",
    helpful: "مفيدة",
    notHelpful: "غير مفيدة",
    getAIHelp: "الحصول على مساعدة الذكاء الاصطناعي",
    tutorialWelcome: "مرحباً بك في المنفق الصحيح!",
    tutorialWelcomeDesc: "هذا التطبيق يساعدك على إدارة أموالك بشكل أفضل. دعنا نقوم بجولة سريعة لنظهر لك كيف يعمل كل شيء.",
    tutorialAssessment: "تقييم الصحة المالية",
    tutorialAssessmentDesc: "ابدأ هنا للتحقق من أدائك مع المال. ستحصل على نقاط ونصائح شخصية لتحسين أموالك.",
    tutorialBudget: "مساعد الميزانية",
    tutorialBudgetDesc: "أنشئ خطة ميزانية تناسب دخلك. سيقترح التطبيق أفضل قاعدة ميزانية لوضعك.",
    tutorialAI: "مساعد المال بالذكاء الاصطناعي",
    tutorialAIDesc: "اطرح أسئلة واحصل على مساعدة فورية مع قرارات المال. مثل وجود مستشار مالي متاح 24/7.",
    tutorialAccessibility: "إعدادات إمكانية الوصول",
    tutorialAccessibilityDesc: "اجعل التطبيق يعمل بشكل أفضل لك. غير حجم النص والألوان واللغة والمزيد لتناسب احتياجاتك.",
    tutorialReady: "جاهز للبدء!",
    tutorialReadyDesc: "نوصي بالبدء بتقييم الصحة المالية لفهم وضعك الحالي والحصول على نصائح شخصية.",
    appTutorial: "دليل التطبيق",
    skipTutorial: "تخطي الدليل",
    previous: "السابق",
    next: "التالي",
    startAssessment: "بدء التقييم",
    exploreMyOwn: "استكشاف بمفردي",
    back: "عودة",
    backToOverview: "العودة للنظرة العامة",
    start: "بدء",
    getStarted: "البدء",
    didYouKnow: "هل تعلم؟",
    showAnotherFact: "إظهار حقيقة أخرى",
    skipToMain: "الانتقال للمحتوى الرئيسي",
    checkMoneyHealth: "فحص صحة أموالك",
    checkMoneyHealthDesc: "انظر كيف تسير أمورك مع المال واحصل على مساعدة",
    budgetHelper: "مساعد الميزانية",
    budgetHelperDesc: "ضع خطة لأموالك تناسبك",
    moneyHelperChat: "دردشة مساعد المال",
    moneyHelperChatDesc: "اطرح أسئلة واحصل على مساعدة مع قرارات المال",
    makeAppEasier: "جعل التطبيق أسهل للاستخدام",
    makeAppEasierDesc: "غير شكل وعمل التطبيق ليناسبك",
    invalidInput: "إدخال غير صحيح",
    enterValidIncome: "يرجى إدخال دخل شهري صحيح",
    assessmentComplete: "اكتمل التقييم!",
    scoreMessage: "نقاط صحتك المالية هي",
    thankYou: "شكراً لك!",
    adviceHelpful: "نحن سعداء أن النصيحة كانت مفيدة",
    moreAdvice: "المزيد من النصائح قادمة!",
    additionalTipsDesc: "إليك نصائح إضافية قد تساعد",
    aiHelper: "مساعد الذكاء الاصطناعي",
    navigateToAI: "انتقل لقسم دردشة الذكاء الاصطناعي للحصول على مساعدة شخصية"
  },
  hi: {
    appTitle: "सही खर्च करने वाला",
    appSubtitle: "आपका सुलभ वित्तीय कल्याण साथी",
    welcomeTitle: "अपने वित्तीय भविष्य का नियंत्रण लें",
    welcomeDescription: "चाहे आप पैसे के प्रबंधन में नए हों या अपने वित्तीय स्वास्थ्य में सुधार की तलाश में हों, हम महंगे सलाहकारों की आवश्यकता के बिना सूचित निर्णय लेने में आपकी मदद करने के लिए यहाँ हैं।",
    selectLanguage: "भाषा चुनें",
    languageDescription: "जारी रखने के लिए अपनी पसंदीदा भाषा चुनें",
    continue: "जारी रखें",
    accessibilitySettings: "पहुंच सेटिंग्स",
    textSize: "टेक्स्ट साइज़",
    visualAccessibility: "दृश्य पहुंच",
    screenReaderSupport: "स्क्रीन रीडर सपोर्ट",
    language: "भाषा",
    interfaceMode: "इंटरफेस मोड",
    simple: "सरल",
    detailed: "विस्तृत",
    small: "छोटा",
    medium: "मध्यम",
    large: "बड़ा",
    extraLarge: "अतिरिक्त बड़ा",
    highContrastMode: "उच्च कंट्रास्ट मोड",
    enhancedScreenReaderMode: "बेहतर स्क्रीन रीडर मोड",
    simpleMode: "सरल मोड",
    simpleModeDescription: "बुनियादी भाषा और सरल इंटरफेस का उपयोग करें",
    detailedMode: "विस्तृत मोड",
    detailedModeDescription: "उन्नत विकल्प और तकनीकी शब्द दिखाएं",
    makeColorsStronger: "रंगों को और तेज़ बनाएं",
    colorsAdjusted: "रंग समायोजित किए गए हैं",
    makeTextEasierToSee: "तेज़ रंगों के साथ टेक्स्ट को देखना आसान बनाता है",
    increaseContrastDesc: "बेहतर दृश्यता के लिए टेक्स्ट और बैकग्राउंड के बीच कंट्रास्ट बढ़ाता है",
    helpForScreenReaders: "स्क्रीन रीडर के लिए मदद",
    interfaceAdjustedForScreenReaders: "स्क्रीन रीडर के लिए इंटरफेस समायोजित किया गया",
    worksWithScreenReaderSoftware: "स्क्रीन रीडर सॉफ्टवेयर के साथ ऐप को बेहतर काम करने में मदद करता है",
    optimizesInterfaceElements: "इंटरफेस तत्वों को अनुकूलित करता है और स्क्रीन रीडर के लिए अतिरिक्त संदर्भ जोड़ता है",
    makeAppEasierToUse: "ऐप को आपके लिए उपयोग में आसान बनाएं",
    customizeAccessibilityNeeds: "अपनी पहुंच आवश्यकताओं को पूरा करने के लिए ऐप को अनुकूलित करें",
    easyWordsBasicOptions: "आसान शब्द और बुनियादी विकल्प",
    moreOptionsTechnicalWords: "अधिक विकल्प और तकनीकी शब्द",
    textSizeOptions: "टेक्स्ट साइज़ विकल्प",
    fontSizeOptions: "फ़ॉन्ट साइज़ विकल्प",
    makeText: "टेक्स्ट बनाएं",
    setFontSizeTo: "फ़ॉन्ट साइज़ सेट करें",
    languageOptions: "भाषा विकल्प",
    languageSelection: "भाषा चयन",
    changeLanguageTo: "भाषा बदलें",
    setLanguageTo: "भाषा सेट करें",
    goTo: "जाएं",
    quickAccessTips: "त्वरित पहुंच सुझाव",
    navigateBetweenElements: "तत्वों के बीच नेविगेट करें",
    activateButtons: "बटन सक्रिय करें",
    closeDialogsReturn: "डायलॉग बंद करें या पिछले अनुभाग पर वापस जाएं",
    increaseBrowserZoom: "ब्राउज़र ज़ूम बढ़ाएं",
    textSizeChanged: "टेक्स्ट साइज़ बदल गया",
    textIsNow: "टेक्स्ट अब है",
    fontSizeUpdated: "फ़ॉन्ट साइज़ अपडेट किया गया",
    fontSizeChangedTo: "फ़ॉन्ट साइज़ बदला गया",
    colorsBackToNormal: "रंग सामान्य पर वापस आ गए",
    highContrastOn: "उच्च कंट्रास्ट चालू",
    highContrastDisabled: "उच्च कंट्रास्ट अक्षम",
    highContrastEnabled: "उच्च कंट्रास्ट सक्षम",
    visualContrastAdjusted: "दृश्य कंट्रास्ट समायोजित किया गया",
    screenReaderHelpOff: "स्क्रीन रीडर मदद बंद",
    screenReaderHelpOn: "स्क्रीन रीडर मदद चालू",
    screenReaderModeDisabled: "स्क्रीन रीडर मोड अक्षम",
    screenReaderModeEnabled: "स्क्रीन रीडर मोड सक्षम",
    interfaceOptimizedForScreenReaders: "स्क्रीन रीडर के लिए इंटरफेस अनुकूलित",
    simpleModeOn: "सरल मोड चालू",
    detailedModeOn: "विस्तृत मोड चालू",
    usingSimpleLanguage: "सरल भाषा और बुनियादी विकल्पों का उपयोग",
    showingAdvancedOptions: "उन्नत विकल्प और तकनीकी शब्द दिखा रहे हैं",
    financialHealthAssessment: "वित्तीय स्वास्थ्य मूल्यांकन",
    financialHealthDescription: "व्यक्तिगत स्कोर और सुझाव प्राप्त करने के लिए अपनी वित्तीय जानकारी दर्ज करें",
    monthlyIncome: "मासिक आय ($)",
    monthlyExpenses: "मासिक खर्चे ($)",
    totalSavings: "कुल बचत ($)",
    totalDebt: "कुल कर्ज़ ($)",
    emergencyFund: "आपातकालीन फंड ($)",
    calculateScore: "मेरा वित्तीय स्वास्थ्य स्कोर गिनें",
    yourScore: "आपका वित्तीय स्वास्थ्य स्कोर",
    excellent: "उत्कृष्ट",
    good: "अच्छा",
    fair: "ठीक-ठाक",
    needsImprovement: "सुधार की आवश्यकता",
    savingsRate: "बचत दर",
    emergencyMonths: "आपातकालीन महीने",
    debtToIncome: "कर्ज़ से आय अनुपात",
    recommendations: "व्यक्तिगत सुझाव:",
    additionalTips: "अतिरिक्त सुझाव:",
    wasHelpful: "क्या यह सलाह उपयोगी थी?",
    helpful: "उपयोगी",
    notHelpful: "उपयोगी नहीं",
    getAIHelp: "AI मदद प्राप्त करें",
    tutorialWelcome: "सही खर्च करने वाले में आपका स्वागत है!",
    tutorialWelcomeDesc: "यह ऐप आपको अपने पैसे को बेहतर तरीके से प्रबंधित करने में मदद करता है। आइए एक त्वरित दौरा करें और दिखाएं कि सब कुछ कैसे काम करता है।",
    tutorialAssessment: "वित्तीय स्वास्थ्य मूल्यांकन",
    tutorialAssessmentDesc: "पैसे के साथ आप कैसा कर रहे हैं यह जांचने के लिए यहां शुरू करें। आपको अपने वित्त को बेहतर बनाने के लिए एक स्कोर और व्यक्तिगत सलाह मिलेगी।",
    tutorialBudget: "बजट सहायक",
    tutorialBudgetDesc: "अपनी आय के लिए काम करने वाली बजट योजना बनाएं। ऐप आपकी स्थिति के लिए सबसे अच्छा बजट नियम सुझाएगा।",
    tutorialAI: "AI पैसा सहायक",
    tutorialAIDesc: "सवाल पूछें और पैसे के निर्णयों के साथ तुरंत मदद प्राप्त करें। यह 24/7 उपलब्ध वित्तीय सलाहकार रखने जैसा है।",
    tutorialAccessibility: "पहुंच सेटिंग्स",
    tutorialAccessibilityDesc: "ऐप को आपके लिए बेहतर काम करने दें। अपनी आवश्यकताओं के अनुसार टेक्स्ट साइज़, रंग, भाषा और अधिक बदलें।",
    tutorialReady: "शुरू करने के लिए तैयार!",
    tutorialReadyDesc: "हम आपकी वर्तमान स्थिति को समझने और व्यक्तिगत सलाह प्राप्त करने के लिए वित्तीय स्वास्थ्य मूल्यांकन से शुरुआत करने की सलाह देते हैं।",
    appTutorial: "ऐप ट्यूटोरियल",
    skipTutorial: "ट्यूटोरियल छोड़ें",
    previous: "पिछला",
    next: "अगला",
    startAssessment: "मूल्यांकन शुरू करें",
    exploreMyOwn: "अपने आप खोजें",
    back: "वापस",
    backToOverview: "अवलोकन पर वापस",
    start: "शुरू करें",
    getStarted: "शुरुआत करें",
    didYouKnow: "क्या आप जानते थे?",
    showAnotherFact: "दूसरा तथ्य दिखाएं",
    skipToMain: "मुख्य सामग्री पर जाएं",
    checkMoneyHealth: "अपने पैसे का स्वास्थ्य जांचें",
    checkMoneyHealthDesc: "देखें कि आप पैसे के साथ कैसा कर रहे हैं और मदद प्राप्त करें",
    budgetHelper: "बजट सहायक",
    budgetHelperDesc: "अपने पैसे के लिए एक योजना बनाएं जो आपके लिए काम करे",
    moneyHelperChat: "पैसा सहायक चैट",
    moneyHelperChatDesc: "सवाल पूछें और पैसे के निर्णयों के साथ मदद प्राप्त करें",
    makeAppEasier: "ऐप को उपयोग में आसान बनाएं",
    makeAppEasierDesc: "ऐप कैसे दिखता है और काम करता है इसे अपने लिए बदलें",
    invalidInput: "अमान्य इनपुट",
    enterValidIncome: "कृपया एक वैध मासिक आय दर्ज करें",
    assessmentComplete: "मूल्यांकन पूरा हुआ!",
    scoreMessage: "आपका वित्तीय स्वास्थ्य स्कोर है",
    thankYou: "धन्यवाद!",
    adviceHelpful: "हमें खुशी है कि सलाह उपयोगी थी",
    moreAdvice: "और सलाह आ रही है!",
    additionalTipsDesc: "यहां अतिरिक्त सुझाव हैं जो मदद कर सकते हैं",
    aiHelper: "AI सहायक",
    navigateToAI: "व्यक्तिगत सहायता के लिए AI चैट अनुभाग पर जाएं"
  }
};

const AccessibilityContext = createContext<AccessibilityContextType | undefined>(undefined);

export const useAccessibility = () => {
  const context = useContext(AccessibilityContext);
  if (!context) {
    throw new Error("useAccessibility must be used within AccessibilityProvider");
  }
  return context;
};

interface AccessibilityProviderProps {
  children: ReactNode;
}

export const AccessibilityProvider = ({ children }: AccessibilityProviderProps) => {
  const [fontSize, setFontSize] = useState("medium");
  const [highContrast, setHighContrast] = useState(false);
  const [screenReaderMode, setScreenReaderMode] = useState(false);
  const [language, setLanguage] = useState("en");
  const [simpleMode, setSimpleMode] = useState(true);

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  const announceToScreenReader = (message: string) => {
    const announcement = document.createElement("div");
    announcement.setAttribute("aria-live", "polite");
    announcement.setAttribute("aria-atomic", "true");
    announcement.setAttribute("class", "sr-only");
    announcement.textContent = message;
    document.body.appendChild(announcement);
    
    setTimeout(() => {
      document.body.removeChild(announcement);
    }, 1000);
  };

  useEffect(() => {
    const savedPrefs = localStorage.getItem("accessibility-preferences");
    if (savedPrefs) {
      try {
        const prefs = JSON.parse(savedPrefs);
        setFontSize(prefs.fontSize || "medium");
        setHighContrast(prefs.highContrast || false);
        setScreenReaderMode(prefs.screenReaderMode || false);
        setLanguage(prefs.language || "en");
        setSimpleMode(prefs.simpleMode !== undefined ? prefs.simpleMode : true);
        console.log("Loaded accessibility preferences:", prefs);
      } catch (error) {
        console.error("Error loading accessibility preferences:", error);
        // Use defaults if parsing fails
      }
    }
  }, []);

  useEffect(() => {
    const prefs = {
      fontSize,
      highContrast,
      screenReaderMode,
      language,
      simpleMode
    };
    
    try {
      localStorage.setItem("accessibility-preferences", JSON.stringify(prefs));
      console.log("Saved accessibility preferences:", prefs);
    } catch (error) {
      console.error("Error saving accessibility preferences:", error);
    }
    
    // Apply font size
    const root = document.documentElement;
    switch (fontSize) {
      case "small":
        root.style.fontSize = "14px";
        break;
      case "large":
        root.style.fontSize = "18px";
        break;
      case "extra-large":
        root.style.fontSize = "22px";
        break;
      default:
        root.style.fontSize = "16px";
    }

    // Apply contrast
    document.body.classList.toggle("high-contrast", highContrast);
    
    // Apply screen reader mode
    document.body.classList.toggle("screen-reader-mode", screenReaderMode);
    
    // Apply simple mode
    document.body.classList.toggle("simple-mode", simpleMode);
  }, [fontSize, highContrast, screenReaderMode, language, simpleMode]);

  const value = {
    fontSize,
    highContrast,
    screenReaderMode,
    language,
    simpleMode,
    setFontSize,
    setHighContrast,
    setScreenReaderMode,
    setLanguage,
    setSimpleMode,
    announceToScreenReader,
    t
  };

  return (
    <AccessibilityContext.Provider value={value}>
      {children}
    </AccessibilityContext.Provider>
  );
};
